import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(() => {
        // Get language from localStorage or default to 'vi'
        return localStorage.getItem('language') || 'vi';
    });

    useEffect(() => {
        localStorage.setItem('language', language);
    }, [language]);

    const toggleLanguage = () => {
        setLanguage(prev => prev === 'vi' ? 'en' : 'vi');
    };

    const translations = {
        vi: {
            // Navbar
            home: 'TRANG CHỦ',
            features: 'TÍNH NĂNG',
            pricing: 'GIÁ CẢ',
            download: 'TẢI XUỐNG',
            contact: 'LIÊN HỆ',
            login: 'ĐĂNG NHẬP',
            register: 'ĐĂNG KÝ',
            language: 'Ngôn ngữ',
            country: 'Quốc gia/khu vực',
            // Navbar extra
            navForFamily: 'Dành cho gia đình',
            navForBusiness: 'Dành cho doanh nghiệp',
            navPartners: 'Đối tác',
            navAboutUs: 'Giới thiệu về Chúng tôi',
            familyHeader: 'Dành cho gia đình',
            businessHeader: 'Dành cho doanh nghiệp',
            partnersHeader: 'Đối tác',
            aboutHeader: 'Giới thiệu về Chúng tôi',
            mobileAccount: 'Tài khoản',
            viewAllSolutions: 'Xem tất cả các giải pháp',
            viewAllBusinessSolutions: 'Xem tất cả giải pháp doanh nghiệp',
            // Navbar labels
            securitySolutions: 'Giải pháp bảo mật',
            privacyAndKids: 'Quyền riêng tư & Trẻ nhỏ',
            licenseRenewal: 'Gia hạn giấy phép',
            support: 'Hỗ trợ',
            trialsAndDownloads: 'Bản dùng thử & Bản tải xuống',
            businessSolutions: 'Giải pháp doanh nghiệp',
            enterpriseSecurityLabel: 'BẢO MẬT DOANH NGHIỆP',
            centralizedMgmtLabel: 'QUẢN LÝ TẬP TRUNG',
            cloudSecurityLabel: 'BẢO MẬT CLOUD',
            downloads: 'Các bản tải về',
            businessSupport: 'Hỗ trợ doanh nghiệp',
            trainingAndCerts: 'Đào tạo & Chứng chỉ',
            partnerProgram: 'Chương trình đối tác',
            findPartners: 'Tìm đối tác',
            providersForBusiness: 'Các đơn vị cung cấp cho doanh nghiệp',
            providersForConsumers: 'Các đơn vị cung cấp giải pháp tiêu dùng',
            distributorsPartners: 'Hợp tác với các đơn vị phân phối',
            findLearningCenter: 'Tìm một trung tâm học tập',
            becomePartner: 'Trở thành đối tác',
            unitedPortal: 'Cổng đối tác Kidolock United',
            becomeB2B: 'Trở thành đối tác B2B',
            becomeB2C: 'Trở thành đối tác B2C',
            bestSeller: 'SẢN PHẨM BÁN CHẠY NHẤT',
            familyPremiumTier: 'BẢO VỆ CAO CẤP',
            familyAdvancedTier: 'BẢO VỆ NÂNG CAO',
            familyStandardTier: 'BẢO VỆ TIÊU CHUẨN',
            premiumName: 'Kidolock Premium',
            plusName: 'Kidolock Plus',
            standardName: 'Kidolock Standard',
            premiumDesc: 'Bảo vệ toàn diện cho các thiết bị, quyền riêng tư & danh tính trực tuyến của bạn',
            plusDesc: 'Kết hợp các tính năng bảo mật, hiệu năng & quyền riêng tư trong một ứng dụng',
            standardDesc: 'Bảo vệ nâng cao kèm công cụ tăng cường hiệu năng thiết bị',
            userMgmtLabel: 'CHỨC NĂNG QUẢN LÝ NGƯỜI DÙNG',
            safeKidsName: 'Kidolock Safe Kids',
            safeKidsDesc: 'Giải pháp kiểm soát linh hoạt dành cho cha mẹ & thiết bị theo dõi qua GPS dành cho con bạn.',
            vpnLabel: 'VPN',
            vpnName: 'Kidolock VPN Secure Connection',
            vpnDesc: 'VPN riêng tư và bảo mật để tận hưởng internet mà không phải đánh đổi bằng tốc độ.',
            pwdProtectLabel: 'BẢO VỆ MẬT KHẨU',
            pwdMgrName: 'Kidolock Password Manager',
            pwdMgrDesc: 'Kho bảo mật cấp ngân hàng cho mật khẩu & tài liệu của bạn.',
            businessSecurityName: 'Kidolock Business Security',
            businessSecurityDesc: 'Bảo vệ toàn diện cho mạng doanh nghiệp, endpoint và dữ liệu quan trọng',
            enterpriseSecurityName: 'Kidolock Enterprise Security',
            enterpriseSecurityDesc: 'Giải pháp quản lý bảo mật tập trung cho doanh nghiệp lớn',
            cloudSecurityName: 'Kidolock Cloud Security',
            cloudSecurityDesc: 'Bảo vệ dữ liệu và ứng dụng trên cloud một cách an toàn',
            aboutUs: 'Về chúng tôi',
            learnAboutUs: 'Tìm hiểu về chúng tôi',
            contactUs: 'Liên hệ với chúng tôi',
            careers: 'Nghề nghiệp',
            media: 'Truyền thông',
            pressCenter: 'Trung tâm báo chí',
            pressReleases: 'Thông cáo báo chí',
            sponsorships: 'Tài trợ',
            wallet: 'Ví gói',
            purchaseHistory: 'Lịch sử mua hàng',
            comingSoon: 'Sắp có',
            logoutLabel: 'Đăng xuất',
            loginLabel: 'Đăng nhập',
            registerLabel: 'Đăng ký',
            adminLabel: 'Quản trị viên',
            parentLabel: 'Phụ huynh',
            adminRole: 'ADMIN',
            premiumRole: 'PREMIUM',
            mobileAccount: 'Tài khoản',
            
            // HomePage Banner
            breadcrumbHome: 'TRANG CHỦ',
            breadcrumbKidolock: 'KIDOLOCK',
            mainTitle: 'KIDOLOCK',
            subtitle1: 'GIẢI PHÁP PHẦN MỀM',
            subtitle2: 'BẢO VỆ VÀ NGĂN CHẶN',
            subtitle3_prefix: '',
            subtitle3_highlight_trash_internet: 'RÁC INTERNET',
            subtitle3_suffix: ' CHO TRẺ EM',
            feature1_prefix: 'QUẢN LÝ NHỮNG GÌ CON TRẺ THEO DÕI TRÊN ',
            feature1_highlight_internet: 'INTERNET',
            feature1_suffix: '',
            feature2_prefix: 'KIỂM SOÁT QUỸ THỜI GIAN ',
            feature2_highlight_online: 'ONLINE',
            feature2_suffix: ' CỦA TRẺ',
            feature3_prefix: 'CHA MẸ AN TÂM, TỪ ',
            feature3_highlight_anywhere: 'BẤT CỨ ĐÂU',
            feature3_suffix: '',
            availableOn: 'AVAILABLE ON',
            
            // WhyKidolock
            whyTitle1: 'TẠI SAO LẠI LÀ',
            whyTitle2: 'KIDOLOCK ?',
            trackTitle: 'THEO DÕI',
            trackContent: 'Phần mềm quản lý trẻ em trên điện thoại và máy tính giúp bạn biết con bạn đang ở đâu 24/7, theo dõi hoạt động kỹ thuật số và thời gian sử dụng thiết bị của các con, đồng thời nhận cảnh báo về những hành vi đáng lo ngại.',
            educateTitle: 'GIÁO DỤC',
            educateContent: 'Nuôi dưỡng những thói quen tích cực bằng cách dạy về an toàn kỹ thuật số và khuyến khích việc cân bằng hoạt động giữa trực tuyến và ngoại tuyến',
            protectTitle: 'BẢO VỆ',
            protectContent: 'Bảo vệ con bạn khỏi những trải nghiệm tiêu cực trên các thiết bị bằng cách chặn nội dung độc hại.',
            
            // FeaturesSection
            featuresTitle1: 'TẤT CẢ TÍNH NĂNG KIỂM SOÁT MÀ',
            featuresTitle2: 'PHỤ HUYNH CẦN',
            featuresSubtitle: 'Theo dõi con bạn với đa dạng thiết bị',
            feature1: 'Tích hợp đồng bộ từ đa dạng nền tảng, hệ điều hành',
            feature2: 'Dữ liệu trực quan hóa, dễ hiểu, dễ theo dõi',
            feature3: 'Dễ dàng quản lý kiểm soát với cảnh báo hệ thống đến mọi thiết bị',
            
            // ProtectionSection
            protectionTitle: 'BẢO VỆ CON BẠN KHỎI NHỮNG TRẢI NGHIỆM TIÊU CỰC',
            protectionFeature1: 'Ngăn chặn các truy cập độc hại với tính năng hạn chế tìm kiếm',
            protectionFeature2: 'Ẩn các kết quả tìm kiếm, nội dung tiêu cực, gây ảnh hưởng xấu đến tâm lý trẻ',
            
            // EducationSection
            educationTitle: 'GIÁO DỤC CON CÁI VỀ NHỮNG THÓI QUEN TÍCH CỰC',
            educationFeature1: 'Đặt các giới hạn thời gian hàng ngày cho các ứng dụng cụ thể với tính năng kiểm soát việc sử dụng ứng dụng',
            educationFeature2: 'Nuôi dưỡng những thói quen kỹ thuật số lành mạnh với tính năng lập lịch cho thiết bị',
            
            // TestimonialsSection
            testimonialsTitle1: 'PHỤ HUYNH',
            testimonialsTitle2: 'NÓI GÌ ?',
            testimonial1Title: 'QUÁ ỔN',
            testimonial1Content: 'Giờ đây, tôi có thể giới hạn việc truy cập của con tôi vào các trang web nhất định trong những giờ cụ thể hoặc chỉ cần tắt máy tính hoàn toàn. Tôi nhận được thông báo ngay lập tức khi con tôi cố truy cập các trang web không được khuyến nghị hoặc bị cấm.',
            testimonial2Title: 'HOÀN HẢO',
            testimonial2Content: 'Tôi thích ứng dụng này. Nó cho phép tôi theo dõi hoạt động của con tôi và kiểm soát thời điểm con có thể truy cập các trang web nhất định. Tôi thích việc con có thể yêu cầu quyền truy cập từ máy tính xách tay của mình và sau đó tôi có thể chỉ cần phê duyệt hoặc từ chối yêu cầu này từ điện thoại của tôi.',
            testimonial3Title: 'VƯỢT KÌ VỌNG',
            testimonial3Content: 'Tôi có thể cập nhật hơn cả mong đợi những gì tôi muốn biết về cuộc sống số của các con tôi. Tôi có thể biết chúng đang ở đâu, đã ở đâu và thậm chí báo cho chúng biết liệu có cần sạc pin trong iPhones của chúng hay không – và tôi đang sử dụng Android mà không gặp vấn đề gì.',
            
            // PricingSection
            pricingSubtitle: 'CÁC GÓI DỊCH VỤ',
            pricingTitle1: 'CHỌN GÓI PHÙ HỢP',
            pricingTitle2: 'VỚI BẠN',
            otherPackages: 'CÁC GÓI KHÁC',
            viewDetails: 'XEM CHI TIẾT',
            loadingPackages: 'Đang tải gói dịch vụ...',
            deviceUser: '1 thiết bị | 1 người dùng',
            freeTrial: 'GÓI DÙNG THỬ',
            free: 'MIỄN PHÍ',
            
            // DownloadSection
            downloadHeader1: 'TẢI APP NGAY TẠI',
            downloadHeader2Left: 'MỌI NỀN TẢNG',
            downloadHeader2Right: 'THIẾT BỊ',
            downloadExe: 'TẢI FILE EXE',
            forAllDevices: 'Cho tất cả thiết bị',
            requiresInternet: 'Yêu cầu có kết nối internet',
            systemRequirements: 'Yêu cầu về hệ thống',
            windowsTitle: 'Máy tính để bàn và máy tính xách tay chạy Windows®',
            diskSpace: 'Dung lượng ổ đĩa',
            freeDiskSpace: 'dung lượng trống trên ổ cứng',
            cpu: 'Bộ xử lý',
            orHigher: 'trở lên',
            or: 'hoặc',
            memory: 'Bộ nhớ',
            minScreenRes: 'Độ phân giải màn hình tối thiểu',
            androidTitle: 'Điện thoại thông minh và máy tính bảng Android¹',
            os: 'Hệ điều hành',
            iosTitle: 'iPhone và iPad',
            languageSupport: 'Hỗ trợ ngôn ngữ',
            vietnamese: 'Tiếng Việt',
            vietnameseDesc: 'Đảm bảo tính dễ hiểu, dễ sử dụng của hệ thống ở tất cả các nền tảng',
            english: 'Tiếng Anh',
            englishDesc: 'Dịch thuật chuẩn, đảm bảo hỗ trợ song ngữ cho đa dạng người dùng',
            
            // Contact addresses (values)
            addressMainValue: 'Phòng 901B nhà Thí Nghiệm, Trường Đại học Xây Dựng Hà Nội, số 55 Giải Phóng, Hà Nội',
            address2Value: 'Khu vực trường Kiến Trúc - Văn Quán, Hà Đông, Hà Nội',
            address3Value: 'Trung Tâm Bồi Dưỡng Chính Trị Quận Phú Nhuận - Số 178 Đường Lê Văn Sỹ, P.10, Q. Phú Nhuận, TPHCM',
            address4Value: 'Trường Cao Đẳng Xây Dựng TPHCM, SỐ 190, Võ Văn Ngân, P.Linh Chiểu, Q. Thủ Đức, TPHCM',

            // SubscriptionWorkflowSection
            subscriptionHeader1: 'CÁCH THỨC HOẠT ĐỘNG CỦA',
            subscriptionHeader2: 'GÓI ĐĂNG KÝ',
            pricingLevels: 'CÁC MỨC GIÁ',
            subscriptionCommonDesc: 'Gói đăng ký của bạn sẽ tự động gia hạn mỗi kỳ cho đến khi bạn hủy bỏ gói đăng ký. Để đảm bảo chức năng bảo vệ không bị gián đoạn, chúng tôi sẽ cố gắng tính phí qua phương thức thanh toán của bạn 20 ngày trước khi gói đăng ký của bạn kết thúc. Chúng tôi sẽ thông báo cho bạn về lần tự động gia hạn sắp tới qua email.',
            autoRenewal: 'TỰ ĐỘNG GIA HẠN',
            cancelAutoRenewal: 'HỦY BỎ TỰ ĐỘNG GIA HẠN',
            cancelIntro1: 'Bạn có thể hủy bỏ tự động gia hạn gói đăng ký của mình bất cứ lúc nào.',
            cancelIntro2: 'Nếu bạn hủy bỏ, bạn sẽ được bảo vệ đầy đủ đến khi kết thúc kỳ mà đã thanh toán. Sau ngày này, gói đăng ký của bạn sẽ kết thúc và bạn sẽ không bị tính phí cho bất kỳ khoảng thời gian nào sau này.',
            cancelHowTo: 'Để hủy bỏ:',
            cancelList1: 'Mở biên nhận qua email mà bạn nhận được sau lần mua hàng đầu tiên hoặc email có nhắc nhở tự động gia hạn.',
            cancelList2: 'Truy cập vào liên kết đến trang chứa các điều kiện tự động gia hạn gói đăng ký của bạn.',
            cancelList3: 'Chọn Hủy bỏ tự động gia hạn. Bạn sẽ sớm nhận được email xác nhận việc hủy bỏ tự động gia hạn.',
            cancelSupport: 'Bạn cũng có thể hủy bỏ tự động gia hạn bằng cách liên hệ với bộ phận Hỗ trợ khách hàng của Kidolock.',
            refundIntro: 'Nếu bạn đã bị trừ tiền cho kỳ gói đăng ký tiếp theo, bạn có 30 ngày kể từ ngày thanh toán để yêu cầu hoàn lại toàn bộ khoản thanh toán gia hạn.',
            refundContact: 'Để yêu cầu hoàn tiền, vui lòng liên hệ với bộ phận Hỗ trợ khách hàng của Kidolock.',
            
            // ContactSection
            contactTitle: 'HÃY ĐỂ CHÚNG TÔI LIÊN LẠC VỚI BẠN',
            emailPlaceholder: 'nhập email của bạn',
            send: 'GỬI',
            rdsicTitle: 'HỆ THỐNG ĐÀO TẠO RDSIC',
            rdsicSubtitle: 'Thương hiệu thuộc Viện Tin Học Xây Dựng, Trường Đại Học Xây Dựng Hà Nội',
            mainOffice: 'Trụ sở chính :',
            trainingAddress2: 'Địa chỉ đào tạo 2 :',
            trainingAddress3: 'Địa chỉ đào tạo 3 :',
            trainingAddress4: 'Địa chỉ đào tạo 4 :',
            contactInfo: 'THÔNG TIN LIÊN HỆ',
            hotline: 'Hotline :',
            email: 'Email :',
            website: 'Website :',
            products: 'SẢN PHẨM',
            copyright: '@2025 RDSIC ALL RIGHTS RESERVED',
            
            // Auth Pages
            loginTitle: 'ĐĂNG NHẬP',
            registerTitle: 'ĐĂNG KÝ',
            resetPasswordTitle: 'ĐẶT LẠI MẬT KHẨU',
            changePasswordTitle: 'ĐỔI MẬT KHẨU',
            emailLabel: 'Email',
            phoneLabel: 'Số điện thoại',
            passwordLabel: 'Mật khẩu',
            confirmPasswordLabel: 'Xác nhận mật khẩu',
            newPasswordLabel: 'Mật khẩu mới',
            currentPasswordLabel: 'Mật khẩu hiện tại',
            forgotPassword: 'Quên mật khẩu?',
            rememberMe: 'Ghi nhớ đăng nhập',
            loginButton: 'ĐĂNG NHẬP',
            registerButton: 'ĐĂNG KÝ',
            resetPasswordButton: 'ĐẶT LẠI MẬT KHẨU',
            changePasswordButton: 'ĐỔI MẬT KHẨU',
            backToLogin: 'Quay lại đăng nhập',
            alreadyHaveAccount: 'Đã có tài khoản?',
            dontHaveAccount: 'Chưa có tài khoản?',
            createAccount: 'Tạo tài khoản',
            loginHere: 'Đăng nhập tại đây',
            // Register page extra
            infoStep: 'Thông tin',
            verifyStep: 'Xác thực',
            fillAllFields: 'Vui lòng điền đầy đủ thông tin',
            pwdNotMeet: 'Mật khẩu chưa đáp ứng yêu cầu bảo mật',
            confirmPwdNotMatch: 'Mật khẩu xác nhận không khớp',
            invalidEmail: 'Email không hợp lệ',
            invalidPhone: 'Số điện thoại không hợp lệ',
            otpSent: 'Mã OTP đã được gửi đến số điện thoại của bạn',
            enterOTP: 'Vui lòng nhập mã OTP',
            registerSuccess: 'Đăng ký thành công!',
            sendingOTP: 'Đang gửi OTP...',
            sendOTP: 'Gửi mã OTP',
            verifyingPhone: 'Xác thực số điện thoại',
            otpSentTo: 'Mã OTP đã được gửi đến số điện thoại:',
            otp: 'Mã OTP',
            otpPlaceholder: 'Nhập mã OTP',
            otpValid5Min: 'Mã OTP có hiệu lực trong 5 phút',
            back: 'Quay lại',
            completingRegister: 'Đang đăng ký...',
            completeRegister: 'Hoàn thành đăng ký',
            orText: 'Hoặc',
            loginWithExisting: 'Đăng nhập với tài khoản có sẵn',
            passwordRequirementsTitle: 'Yêu cầu mật khẩu:',
            reqAtLeast6: 'Ít nhất 6 ký tự',
            reqUpper: 'Có ít nhất 1 chữ in hoa (A-Z)',
            reqLower: 'Có ít nhất 1 chữ in thường (a-z)',
            reqNumber: 'Có ít nhất 1 chữ số (0-9)',
            reqSpecial: 'Có ít nhất 1 ký tự đặc biệt (!@#$%^&*...)',
            confirmPwdMismatch: 'Mật khẩu xác nhận không khớp',
            confirmPwdOk: 'Mật khẩu khớp và đạt yêu cầu',
            emailPlaceholder: 'Nhập email của bạn',
            phoneLabel: 'Số điện thoại',
            phonePlaceholder: 'Nhập số điện thoại',
            fullNameLabel: 'Họ và tên',
            fullNamePlaceholder: 'Nhập họ và tên',
            passwordPlaceholder: 'Nhập mật khẩu (ít nhất 6 ký tự)',
            confirmPasswordPlaceholder: 'Nhập lại mật khẩu',
            // Auth flows extra
            changePwdHeader: 'Đổi mật khẩu',
            changePwdSub: 'Thay đổi mật khẩu của bạn một cách an toàn',
            step1EnterPassword: 'Nhập mật khẩu',
            step2VerifyOTP: 'Xác thực OTP',
            pwdReqTitle: 'Yêu cầu mật khẩu:',
            currentPassword: 'Mật khẩu hiện tại',
            newPassword: 'Mật khẩu mới',
            confirmNewPassword: 'Xác nhận mật khẩu mới',
            sendOTP: 'Gửi mã OTP',
            sendingOTP: 'Đang gửi OTP...',
            verifyOTP: 'Xác thực OTP',
            otpSentToPhone: 'Mã OTP đã được gửi đến số điện thoại của bạn',
            otpCode: 'Mã OTP',
            otpPlaceholder: 'Nhập mã OTP',
            otpValidFor: 'Mã OTP có hiệu lực trong 5 phút',
            back: 'Quay lại',
            changePassword: 'Đổi mật khẩu',
            changingPassword: 'Đang đổi mật khẩu...',
            resetPwdHeader: 'Đặt lại mật khẩu',
            goHome: 'Quay lại trang chủ',
            phoneRegistered: 'Số điện thoại đã đăng ký',
            enterRegisteredPhone: 'Nhập số điện thoại đã đăng ký',
            weWillSendOTP: 'Chúng tôi sẽ gửi mã OTP đến số điện thoại này để xác thực',
            verifyingPhone: 'Xác thực số điện thoại',
            otpSentTo: 'Mã OTP đã được gửi đến số điện thoại:',
            resetting: 'Đang đặt lại...',
            
            // Payment & Wallet
            paymentTitle: 'THANH TOÁN',
            walletTitle: 'VÍ CỦA TÔI',
            packageInfo: 'Thông tin gói',
            paymentMethod: 'Phương thức thanh toán',
            totalAmount: 'Tổng số tiền',
            payNow: 'THANH TOÁN NGAY',
            paymentSuccess: 'Thanh toán thành công!',
            paymentFailed: 'Thanh toán thất bại!',
            transactionHistory: 'Lịch sử giao dịch',
            balance: 'Số dư',
            recharge: 'Nạp tiền',
            withdraw: 'Rút tiền',
            // Payment pages (extra)
            loadingInfo: 'Đang tải thông tin...',
            cannotLoadPackage: 'Không thể tải thông tin gói dịch vụ',
            errorOccurred: 'Có lỗi xảy ra',
            backHome: 'Về trang chủ',
            processingPaymentResult: 'Đang xử lý kết quả thanh toán...',
            paymentNotSuccessful: 'Thanh toán không thành công',
            paymentPageHeader: 'Thanh Toán Gói Dịch Vụ',
            completeYourOrder: 'Hoàn tất đơn hàng của bạn',
            featuresIncluded: 'Tính năng bao gồm:',
            paymentInfoHeader: 'Thông Tin Thanh Toán',
            confirmYourOrder: 'Xác nhận đơn hàng của bạn',
            buyerInfo: 'Thông tin người mua:',
            orderSummary: 'Tóm tắt đơn hàng:',
            numDevices: 'Số thiết bị',
            total: 'Tổng cộng:',
            securedByVNPay: 'Thanh toán được bảo mật bởi VNPay',
            processing: 'Đang xử lý...',
            payVNPay: 'Thanh Toán VNPay',
            backToHome: 'Quay lại trang chủ',
            
            // Admin Pages
            adminDashboard: 'BẢNG ĐIỀU KHIỂN ADMIN',
            manageUsers: 'QUẢN LÝ NGƯỜI DÙNG',
            manageChildren: 'QUẢN LÝ TRẺ EM',
            manageDevices: 'QUẢN LÝ THIẾT BỊ',
            managePackages: 'QUẢN LÝ GÓI DỊCH VỤ',
            reports: 'BÁO CÁO',
            statistics: 'THỐNG KÊ',
            settings: 'CÀI ĐẶT',
            logout: 'ĐĂNG XUẤT',
            
            // Common Actions
            save: 'LƯU',
            cancel: 'HỦY',
            delete: 'XÓA',
            edit: 'SỬA',
            add: 'THÊM',
            search: 'TÌM KIẾM',
            filter: 'LỌC',
            export: 'XUẤT',
            import: 'NHẬP',
            refresh: 'LÀM MỚI',
            loading: 'Đang tải...',
            error: 'Lỗi',
            success: 'Thành công',
            warning: 'Cảnh báo',
            info: 'Thông tin',
            confirm: 'Xác nhận',
            yes: 'Có',
            no: 'Không',
            ok: 'OK',
            close: 'Đóng'
        },
        en: {
            // Navbar
            home: 'HOME',
            features: 'FEATURES',
            pricing: 'PRICING',
            download: 'DOWNLOAD',
            contact: 'CONTACT',
            login: 'LOGIN',
            register: 'REGISTER',
            language: 'Language',
            country: 'Country/Region',
            // Navbar extra
            navForFamily: 'For family',
            navForBusiness: 'For business',
            navPartners: 'Partners',
            navAboutUs: 'About us',
            familyHeader: 'For family',
            businessHeader: 'For business',
            partnersHeader: 'Partners',
            aboutHeader: 'About us',
            mobileAccount: 'Account',
            viewAllSolutions: 'View all solutions',
            viewAllBusinessSolutions: 'View all business solutions',
            // Navbar labels
            securitySolutions: 'Security solutions',
            privacyAndKids: 'Privacy & Kids',
            licenseRenewal: 'License renewal',
            support: 'Support',
            trialsAndDownloads: 'Trials & Downloads',
            businessSolutions: 'Business solutions',
            enterpriseSecurityLabel: 'ENTERPRISE SECURITY',
            centralizedMgmtLabel: 'CENTRALIZED MANAGEMENT',
            cloudSecurityLabel: 'CLOUD SECURITY',
            downloads: 'Downloads',
            businessSupport: 'Business support',
            trainingAndCerts: 'Training & Certifications',
            partnerProgram: 'Partner program',
            findPartners: 'Find partners',
            providersForBusiness: 'Providers for business',
            providersForConsumers: 'Consumer solution providers',
            distributorsPartners: 'Partner with distributors',
            findLearningCenter: 'Find a learning center',
            becomePartner: 'Become a partner',
            unitedPortal: 'Kidolock United partner portal',
            becomeB2B: 'Become a B2B partner',
            becomeB2C: 'Become a B2C partner',
            bestSeller: 'BESTSELLER',
            familyPremiumTier: 'PREMIUM PROTECTION',
            familyAdvancedTier: 'ADVANCED PROTECTION',
            familyStandardTier: 'STANDARD PROTECTION',
            premiumName: 'Kidolock Premium',
            plusName: 'Kidolock Plus',
            standardName: 'Kidolock Standard',
            premiumDesc: 'Comprehensive protection for your devices, privacy & online identity',
            plusDesc: 'Combines security, performance & privacy features in one app',
            standardDesc: 'Enhanced protection with device performance boosting tools',
            userMgmtLabel: 'USER MANAGEMENT FEATURES',
            safeKidsName: 'Kidolock Safe Kids',
            safeKidsDesc: 'Flexible parental controls & GPS tracking for your children.',
            vpnLabel: 'VPN',
            vpnName: 'Kidolock VPN Secure Connection',
            vpnDesc: 'Private and secure VPN to enjoy the internet without sacrificing speed.',
            pwdProtectLabel: 'PASSWORD PROTECTION',
            pwdMgrName: 'Kidolock Password Manager',
            pwdMgrDesc: 'Bank-grade secure vault for your passwords & documents.',
            businessSecurityName: 'Kidolock Business Security',
            businessSecurityDesc: 'Comprehensive protection for enterprise networks, endpoints and critical data',
            enterpriseSecurityName: 'Kidolock Enterprise Security',
            enterpriseSecurityDesc: 'Centralized security management solution for large enterprises',
            cloudSecurityName: 'Kidolock Cloud Security',
            cloudSecurityDesc: 'Secure your data and applications in the cloud safely',
            aboutUs: 'About us',
            learnAboutUs: 'Learn about us',
            contactUs: 'Contact us',
            careers: 'Careers',
            media: 'Media',
            pressCenter: 'Press center',
            pressReleases: 'Press releases',
            sponsorships: 'Sponsorships',
            wallet: 'Wallet',
            purchaseHistory: 'Purchase history',
            comingSoon: 'Coming soon',
            logoutLabel: 'Logout',
            loginLabel: 'Login',
            registerLabel: 'Register',
            adminLabel: 'Administrator',
            parentLabel: 'Parent',
            adminRole: 'ADMIN',
            premiumRole: 'PREMIUM',
            mobileAccount: 'Account',
            
            // HomePage Banner
            breadcrumbHome: 'HOME',
            breadcrumbKidolock: 'KIDOLOCK',
            mainTitle: 'KIDOLOCK',
            subtitle1: 'SOFTWARE SOLUTION',
            subtitle2: 'PROTECT AND BLOCK',
            subtitle3_prefix: '',
            subtitle3_highlight_trash_internet: 'INTERNET JUNK',
            subtitle3_suffix: ' FOR CHILDREN',
            feature1_prefix: 'MANAGE WHAT YOUR CHILDREN TRACK ON ',
            feature1_highlight_internet: 'INTERNET',
            feature1_suffix: '',
            feature2_prefix: 'CONTROL YOUR CHILD\'S ',
            feature2_highlight_online: 'ONLINE',
            feature2_suffix: ' TIME QUOTA',
            feature3_prefix: 'PARENTS PEACE OF MIND, FROM ',
            feature3_highlight_anywhere: 'ANYWHERE',
            feature3_suffix: '',
            availableOn: 'AVAILABLE ON',
            
            // WhyKidolock
            whyTitle1: 'WHY',
            whyTitle2: 'KIDOLOCK ?',
            trackTitle: 'TRACK',
            trackContent: 'Child management software on phones and computers helps you know where your child is 24/7, track digital activities and device usage time of your children, and receive alerts about concerning behaviors.',
            educateTitle: 'EDUCATE',
            educateContent: 'Nurture positive habits by teaching about digital safety and encouraging balance between online and offline activities',
            protectTitle: 'PROTECT',
            protectContent: 'Protect your child from negative experiences on devices by blocking harmful content.',
            
            // FeaturesSection
            featuresTitle1: 'ALL CONTROL FEATURES THAT',
            featuresTitle2: 'PARENTS NEED',
            featuresSubtitle: 'Track your child with diverse devices',
            feature1: 'Synchronized integration from diverse platforms and operating systems',
            feature2: 'Visualized data, easy to understand and track',
            feature3: 'Easy to manage control with system alerts to all devices',
            
            // ProtectionSection
            protectionTitle: 'PROTECT YOUR CHILD FROM NEGATIVE EXPERIENCES',
            protectionFeature1: 'Prevent harmful access with search restriction feature',
            protectionFeature2: 'Hide search results, negative content that adversely affects children\'s psychology',
            
            // EducationSection
            educationTitle: 'EDUCATE CHILDREN ABOUT POSITIVE HABITS',
            educationFeature1: 'Set daily time limits for specific applications with app usage control feature',
            educationFeature2: 'Nurture healthy digital habits with device scheduling feature',
            
            // TestimonialsSection
            testimonialsTitle1: 'PARENTS',
            testimonialsTitle2: 'SAY WHAT ?',
            testimonial1Title: 'TOO GOOD',
            testimonial1Content: 'Now I can limit my child\'s access to certain websites at specific hours or just turn off the computer completely. I get instant notifications when my child tries to access unrecommended or blocked websites.',
            testimonial2Title: 'PERFECT',
            testimonial2Content: 'I like this app. It allows me to track my child\'s activities and control when they can access certain websites. I like that they can request access from their laptop and then I can just approve or deny this request from my phone.',
            testimonial3Title: 'EXCEEDS EXPECTATIONS',
            testimonial3Content: 'I can update more than expected what I want to know about my children\'s digital life. I can know where they are, where they have been and even tell them if they need to charge their iPhones – and I\'m using Android without any problems.',
            
            // PricingSection
            pricingSubtitle: 'SERVICE PACKAGES',
            pricingTitle1: 'CHOOSE THE PACKAGE',
            pricingTitle2: 'THAT SUITS YOU',
            otherPackages: 'OTHER PACKAGES',
            viewDetails: 'VIEW DETAILS',
            loadingPackages: 'Loading packages...',
            deviceUser: '1 device | 1 user',
            freeTrial: 'TRIAL PACKAGE',
            free: 'FREE',
            
            // DownloadSection
            downloadHeader1: 'DOWNLOAD THE APP ON',
            downloadHeader2Left: 'ALL PLATFORMS',
            downloadHeader2Right: 'DEVICES',
            downloadExe: 'DOWNLOAD EXE',
            forAllDevices: 'For all devices',
            requiresInternet: 'Requires internet connection',
            systemRequirements: 'System requirements',
            windowsTitle: 'Windows® desktops and laptops',
            diskSpace: 'Disk space',
            freeDiskSpace: 'free disk space',
            cpu: 'CPU',
            orHigher: 'or higher',
            or: 'or',
            memory: 'Memory',
            minScreenRes: 'Minimum screen resolution',
            androidTitle: 'Android smartphones and tablets¹',
            os: 'Operating system',
            iosTitle: 'iPhone and iPad',
            languageSupport: 'Language support',
            vietnamese: 'Vietnamese',
            vietnameseDesc: 'Ensures ease of understanding and use across all platforms',
            english: 'English',
            englishDesc: 'Accurate translation, providing bilingual support for diverse users',
            
            // Contact addresses (values)
            addressMainValue: 'Room 901B, Laboratory Building, Hanoi University of Civil Engineering, 55 Giai Phong, Hanoi',
            address2Value: 'Architecture University area - Van Quan, Ha Dong, Hanoi',
            address3Value: 'Phu Nhuan District Political Training Center - 178 Le Van Sy Street, Ward 10, Phu Nhuan District, HCMC',
            address4Value: 'Ho Chi Minh City College of Construction, 190 Vo Van Ngan, Linh Chieu Ward, Thu Duc City, HCMC',

            // SubscriptionWorkflowSection
            subscriptionHeader1: 'HOW IT WORKS',
            subscriptionHeader2: 'SUBSCRIPTION',
            pricingLevels: 'PRICING LEVELS',
            subscriptionCommonDesc: 'Your subscription will automatically renew each term until you cancel it. To ensure uninterrupted protection, we will attempt to charge your payment method 20 days before your subscription ends. We will notify you about the upcoming auto-renewal via email.',
            autoRenewal: 'AUTO-RENEWAL',
            cancelAutoRenewal: 'CANCEL AUTO-RENEWAL',
            cancelIntro1: 'You can cancel auto-renewal of your subscription at any time.',
            cancelIntro2: 'If you cancel, you will remain fully protected until the end of the paid term. After this date, your subscription will end and you will not be charged for any future periods.',
            cancelHowTo: 'To cancel:',
            cancelList1: 'Open the receipt email you received after your first purchase or the auto-renewal reminder email.',
            cancelList2: 'Follow the link to the page containing your subscription auto-renewal terms.',
            cancelList3: 'Choose Cancel auto-renewal. You will soon receive a confirmation email of the cancellation.',
            cancelSupport: 'You can also cancel auto-renewal by contacting Kidolock Customer Support.',
            refundIntro: 'If you have already been charged for the next subscription term, you have 30 days from the payment date to request a full refund of the renewal charge.',
            refundContact: 'To request a refund, please contact Kidolock Customer Support.',
            
            // ContactSection
            contactTitle: 'LET US CONTACT YOU',
            emailPlaceholder: 'enter your email',
            send: 'SEND',
            rdsicTitle: 'RDSIC TRAINING SYSTEM',
            rdsicSubtitle: 'Brand of Institute of Construction Informatics, Hanoi University of Civil Engineering',
            mainOffice: 'Main office :',
            trainingAddress2: 'Training address 2 :',
            trainingAddress3: 'Training address 3 :',
            trainingAddress4: 'Training address 4 :',
            contactInfo: 'CONTACT INFORMATION',
            hotline: 'Hotline :',
            email: 'Email :',
            website: 'Website :',
            products: 'PRODUCTS',
            copyright: '@2025 RDSIC ALL RIGHTS RESERVED',
            
            // Auth Pages
            loginTitle: 'LOGIN',
            registerTitle: 'REGISTER',
            resetPasswordTitle: 'RESET PASSWORD',
            changePasswordTitle: 'CHANGE PASSWORD',
            emailLabel: 'Email',
            phoneLabel: 'Phone Number',
            passwordLabel: 'Password',
            confirmPasswordLabel: 'Confirm Password',
            newPasswordLabel: 'New Password',
            currentPasswordLabel: 'Current Password',
            forgotPassword: 'Forgot Password?',
            rememberMe: 'Remember Me',
            loginButton: 'LOGIN',
            registerButton: 'REGISTER',
            resetPasswordButton: 'RESET PASSWORD',
            changePasswordButton: 'CHANGE PASSWORD',
            backToLogin: 'Back to Login',
            alreadyHaveAccount: 'Already have an account?',
            dontHaveAccount: "Don't have an account?",
            createAccount: 'Create Account',
            loginHere: 'Login Here',
            // Register page extra
            infoStep: 'Information',
            verifyStep: 'Verification',
            fillAllFields: 'Please fill in all required fields',
            pwdNotMeet: 'Password does not meet security requirements',
            confirmPwdNotMatch: 'Confirmation password does not match',
            invalidEmail: 'Invalid email',
            invalidPhone: 'Invalid phone number',
            otpSent: 'OTP has been sent to your phone number',
            enterOTP: 'Please enter the OTP',
            registerSuccess: 'Registration successful!',
            sendingOTP: 'Sending OTP...',
            sendOTP: 'Send OTP',
            verifyingPhone: 'Phone verification',
            otpSentTo: 'OTP sent to phone number:',
            otp: 'OTP Code',
            otpPlaceholder: 'Enter OTP code',
            otpValid5Min: 'OTP is valid for 5 minutes',
            back: 'Back',
            completingRegister: 'Registering...',
            completeRegister: 'Complete registration',
            orText: 'Or',
            loginWithExisting: 'Login with existing account',
            passwordRequirementsTitle: 'Password requirements:',
            reqAtLeast6: 'At least 6 characters',
            reqUpper: 'At least 1 uppercase letter (A-Z)',
            reqLower: 'At least 1 lowercase letter (a-z)',
            reqNumber: 'At least 1 digit (0-9)',
            reqSpecial: 'At least 1 special character (!@#$%^&*...)',
            confirmPwdMismatch: 'Confirmation password does not match',
            confirmPwdOk: 'Passwords match and meet requirements',
            emailPlaceholder: 'Enter your email',
            phoneLabel: 'Phone number',
            phonePlaceholder: 'Enter phone number',
            fullNameLabel: 'Full name',
            fullNamePlaceholder: 'Enter full name',
            passwordPlaceholder: 'Enter password (at least 6 characters)',
            confirmPasswordPlaceholder: 'Re-enter password',
            
            // Auth flows extra
            changePwdHeader: 'Change password',
            changePwdSub: 'Change your password securely',
            step1EnterPassword: 'Enter password',
            step2VerifyOTP: 'Verify OTP',
            pwdReqTitle: 'Password requirements:',
            currentPassword: 'Current password',
            newPassword: 'New password',
            confirmNewPassword: 'Confirm new password',
            sendOTP: 'Send OTP',
            sendingOTP: 'Sending OTP...',
            verifyOTP: 'Verify OTP',
            otpSentToPhone: 'OTP has been sent to your phone number',
            otpCode: 'OTP Code',
            otpPlaceholder: 'Enter OTP code',
            otpValidFor: 'OTP is valid for 5 minutes',
            back: 'Back',
            changePassword: 'Change password',
            changingPassword: 'Changing password...',
            resetPwdHeader: 'Reset password',
            goHome: 'Back to home',
            phoneRegistered: 'Registered phone number',
            enterRegisteredPhone: 'Enter registered phone number',
            weWillSendOTP: 'We will send OTP to this phone number for verification',
            verifyingPhone: 'Phone verification',
            otpSentTo: 'OTP sent to phone number:',
            resetting: 'Resetting...',
            
            // Payment & Wallet
            paymentTitle: 'PAYMENT',
            walletTitle: 'MY WALLET',
            packageInfo: 'Package Information',
            paymentMethod: 'Payment Method',
            totalAmount: 'Total Amount',
            payNow: 'PAY NOW',
            paymentSuccess: 'Payment Successful!',
            paymentFailed: 'Payment Failed!',
            transactionHistory: 'Transaction History',
            balance: 'Balance',
            recharge: 'Recharge',
            withdraw: 'Withdraw',
            // Payment pages (extra)
            loadingInfo: 'Loading information...',
            cannotLoadPackage: 'Cannot load package information',
            errorOccurred: 'An error occurred',
            backHome: 'Back to home',
            processingPaymentResult: 'Processing payment result...',
            paymentNotSuccessful: 'Payment not successful',
            paymentPageHeader: 'Service Package Payment',
            completeYourOrder: 'Complete your order',
            featuresIncluded: 'Features included:',
            paymentInfoHeader: 'Payment Information',
            confirmYourOrder: 'Confirm your order',
            buyerInfo: 'Buyer information:',
            orderSummary: 'Order summary:',
            numDevices: 'Devices',
            total: 'Total:',
            securedByVNPay: 'Payment secured by VNPay',
            processing: 'Processing...',
            payVNPay: 'Pay with VNPay',
            backToHome: 'Back to home',
            
            // Admin Pages
            adminDashboard: 'ADMIN DASHBOARD',
            manageUsers: 'MANAGE USERS',
            manageChildren: 'MANAGE CHILDREN',
            manageDevices: 'MANAGE DEVICES',
            managePackages: 'MANAGE PACKAGES',
            reports: 'REPORTS',
            statistics: 'STATISTICS',
            settings: 'SETTINGS',
            logout: 'LOGOUT',
            
            // Common Actions
            save: 'SAVE',
            cancel: 'CANCEL',
            delete: 'DELETE',
            edit: 'EDIT',
            add: 'ADD',
            search: 'SEARCH',
            filter: 'FILTER',
            export: 'EXPORT',
            import: 'IMPORT',
            refresh: 'REFRESH',
            loading: 'Loading...',
            error: 'Error',
            success: 'Success',
            warning: 'Warning',
            info: 'Information',
            confirm: 'Confirm',
            yes: 'Yes',
            no: 'No',
            ok: 'OK',
            close: 'Close'
        }
    };

    const t = (key) => {
        const dict = translations[language] || {};
        return Object.prototype.hasOwnProperty.call(dict, key) ? dict[key] : key;
    };

    const value = {
        language,
        setLanguage,
        toggleLanguage,
        t
    };

    return (
        <LanguageContext.Provider value={value}>
            {children}
        </LanguageContext.Provider>
    );
};
