import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(() => {
        // Get language from localStorage or default to 'vi'
        return localStorage.getItem('language') || 'vi';
    });

    useEffect(() => {
        localStorage.setItem('language', language);
    }, [language]);

    const toggleLanguage = () => {
        setLanguage(prev => prev === 'vi' ? 'en' : 'vi');
    };

    const translations = {
        vi: {
            // Navbar
            home: 'TRANG CHỦ',
            features: 'TÍNH NĂNG',
            pricing: 'GIÁ CẢ',
            download: 'TẢI XUỐNG',
            contact: 'LIÊN HỆ',
            login: 'ĐĂNG NHẬP',
            register: 'ĐĂNG KÝ',
            language: 'Ngôn ngữ',
            country: 'Quốc gia/khu vực',
            // Navbar extra
            navForFamily: 'Dành cho gia đình',
            navForBusiness: 'Dành cho doanh nghiệp',
            navPartners: 'Đối tác',
            navAboutUs: 'Giới thiệu về Chúng tôi',
            familyHeader: 'Dành cho gia đình',
            businessHeader: 'Dành cho doanh nghiệp',
            partnersHeader: 'Đối tác',
            aboutHeader: 'Giới thiệu về Chúng tôi',
            mobileAccount: 'Tài khoản',
            viewAllSolutions: 'Xem tất cả các giải pháp',
            viewAllBusinessSolutions: 'Xem tất cả giải pháp doanh nghiệp',
            // Navbar labels
            securitySolutions: 'Giải pháp bảo mật',
            privacyAndKids: 'Quyền riêng tư & Trẻ nhỏ',
            licenseRenewal: 'Gia hạn giấy phép',
            support: 'Hỗ trợ',
            trialsAndDownloads: 'Bản dùng thử & Bản tải xuống',
            
            // New Navbar structure
            products: 'Sản phẩm',
            mainFeatures: 'Tính năng chính',
            protectionFeatures: 'Tính năng bảo vệ',
            childProtection: 'Bảo vệ trẻ em',
            safeEducation: 'Giáo dục an toàn',
            pricingAndReviews: 'Giá cả & Đánh giá',
            pricingTable: 'Bảng giá',
            reviews: 'Đánh giá',
            download: 'Tải xuống',
            android: 'Android',
            ios: 'iOS',
            windows: 'Windows',
            androidDesc: 'Tải xuống cho Android',
            iosDesc: 'Tải xuống cho iOS',
            windowsDesc: 'Tải xuống cho Windows',
            androidDeveloping: 'Đang phát triển',
            iosDeveloping: 'Đang phát triển',
            windowsWorking: 'Tải xuống cho Windows',
            businessSolutions: 'Giải pháp doanh nghiệp',
            enterpriseSecurityLabel: 'BẢO MẬT DOANH NGHIỆP',
            centralizedMgmtLabel: 'QUẢN LÝ TẬP TRUNG',
            cloudSecurityLabel: 'BẢO MẬT CLOUD',
            downloads: 'Các bản tải về',
            businessSupport: 'Hỗ trợ doanh nghiệp',
            trainingAndCerts: 'Đào tạo & Chứng chỉ',
            partnerProgram: 'Chương trình đối tác',
            findPartners: 'Tìm đối tác',
            providersForBusiness: 'Các đơn vị cung cấp cho doanh nghiệp',
            providersForConsumers: 'Các đơn vị cung cấp giải pháp tiêu dùng',
            distributorsPartners: 'Hợp tác với các đơn vị phân phối',
            findLearningCenter: 'Tìm một trung tâm học tập',
            becomePartner: 'Trở thành đối tác',
            unitedPortal: 'Cổng đối tác Kidolock United',
            becomeB2B: 'Trở thành đối tác B2B',
            becomeB2C: 'Trở thành đối tác B2C',
            bestSeller: 'SẢN PHẨM BÁN CHẠY NHẤT',
            familyPremiumTier: 'BẢO VỆ CAO CẤP',
            familyAdvancedTier: 'BẢO VỆ NÂNG CAO',
            familyStandardTier: 'BẢO VỆ TIÊU CHUẨN',
            premiumName: 'Kidolock Premium',
            plusName: 'Kidolock Plus',
            standardName: 'Kidolock Standard',
            premiumDesc: 'Bảo vệ toàn diện cho các thiết bị, quyền riêng tư & danh tính trực tuyến của bạn',
            plusDesc: 'Kết hợp các tính năng bảo mật, hiệu năng & quyền riêng tư trong một ứng dụng',
            standardDesc: 'Bảo vệ nâng cao kèm công cụ tăng cường hiệu năng thiết bị',
            userMgmtLabel: 'CHỨC NĂNG QUẢN LÝ NGƯỜI DÙNG',
            safeKidsName: 'Kidolock Safe Kids',
            safeKidsDesc: 'Giải pháp kiểm soát linh hoạt dành cho cha mẹ & thiết bị theo dõi qua GPS dành cho con bạn.',
            vpnLabel: 'VPN',
            vpnName: 'Kidolock VPN Secure Connection',
            vpnDesc: 'VPN riêng tư và bảo mật để tận hưởng internet mà không phải đánh đổi bằng tốc độ.',
            pwdProtectLabel: 'BẢO VỆ MẬT KHẨU',
            pwdMgrName: 'Kidolock Password Manager',
            pwdMgrDesc: 'Kho bảo mật cấp ngân hàng cho mật khẩu & tài liệu của bạn.',
            businessSecurityName: 'Kidolock Business Security',
            businessSecurityDesc: 'Bảo vệ toàn diện cho mạng doanh nghiệp, endpoint và dữ liệu quan trọng',
            enterpriseSecurityName: 'Kidolock Enterprise Security',
            enterpriseSecurityDesc: 'Giải pháp quản lý bảo mật tập trung cho doanh nghiệp lớn',
            cloudSecurityName: 'Kidolock Cloud Security',
            cloudSecurityDesc: 'Bảo vệ dữ liệu và ứng dụng trên cloud một cách an toàn',
            aboutUs: 'Về chúng tôi',
            learnAboutUs: 'Tìm hiểu về chúng tôi',
            contactUs: 'Liên hệ với chúng tôi',
            careers: 'Nghề nghiệp',
            media: 'Truyền thông',
            pressCenter: 'Trung tâm báo chí',
            pressReleases: 'Thông cáo báo chí',
            sponsorships: 'Tài trợ',
            wallet: 'Ví gói',
            purchaseHistory: 'Lịch sử mua hàng',
            comingSoon: 'Sắp có',
            logoutLabel: 'Đăng xuất',
            loginLabel: 'Đăng nhập',
            registerLabel: 'Đăng ký',
            adminLabel: 'Quản trị viên',
            parentLabel: 'Phụ huynh',
            adminRole: 'ADMIN',
            premiumRole: 'PREMIUM',
            mobileAccount: 'Tài khoản',
            
            // HomePage Banner
            breadcrumbHome: 'TRANG CHỦ',
            breadcrumbKidolock: 'KIDOLOCK',
            mainTitle: 'KIDOLOCK',
            subtitle1: 'PHẦN MỀM GIÚP CHA MẸ KIỂM SOÁT,',
            subtitle2: 'GIỚI HẠN VÀ BẢO VỆ CON',
            subtitle3_prefix: '',
            subtitle3_highlight_trash_internet: 'KHI SỬ DỤNG INTERNET ',
            subtitle3_suffix: 'MỌI LÚC - MỌI NƠI',
            feature1_prefix: 'THEO DÕI VÀ QUẢN LÝ NHỮNG GÌ CON XEM TRÊN ',
            feature1_highlight_internet: 'INTERNET',
            feature1_suffix: '',
            feature2_prefix: 'GIỚI HẠN THỜI GIAN ',
            feature2_highlight_online: 'ONLINE',
            feature2_suffix: ' CỦA TRẺ',
            feature3_prefix: 'CHA MẸ AN TÂM, GIÁM SÁT TỪ XA QUA ĐIỆN THOẠI HOẶC MÁY TÍNH',
            feature3_highlight_anywhere: '',
            feature3_suffix: '',
            availableOn: 'AVAILABLE ON',
            
            // WhyKidolock
            whyTitle1: 'TẠI SAO LẠI LÀ',
            whyTitle2: 'KIDOLOCK ?',
            protectTitle: 'BẢO VỆ',
            protectContent: 'Ứng dụng công nghệ AI, KidoLock tự động phát hiện và chặn nội dung nguy hiểm như bạo lực, cờ bạc hay khiêu dâm. Phụ huynh có thể hoàn toàn yên tâm khi con học tập và khám phá Internet mỗi ngày.',
            trackTitle: 'THEO DÕI',
            trackContent: 'Kidolock giúp bố mẹ theo dõi hoạt động trực tuyến của con một cách tinh tế và an toàn — để hiểu con hơn, định hướng tốt hơn, và bảo vệ con khỏi các nguy cơ trên Internet.',
            educateTitle: 'GIÁO DỤC',
            educateContent: 'Cơ chế "thưởng – phạt" thông minh biến việc học thành thói quen chủ động. Trẻ có thể được thưởng thêm thời gian giải trí khi hoàn thành bài tập, tạo động lực học tập tích cực và tự giác hơn mỗi ngày.',
            
            // FeaturesSection
            featuresTitle1: 'THEO DÕI HOẠT ĐỘNG CỦA TRẺ',
            featuresTitle2: '',
            featuresSubtitle: 'Giúp cha mẹ theo dõi toàn bộ hoạt động máy tính của con một cách an toàn và trực quan:',
            feature1: 'Ghi lại lịch sử truy cập website và phần mềm sử dụng',
            feature2: 'Chụp ảnh màn hình định kỳ để cha mẹ dễ dàng kiểm soát',
            feature3: 'Thống kê chi tiết thời gian sử dụng từng website, ứng dụng',
            feature4: 'Đồng bộ toàn bộ dữ liệu và báo cáo lên ứng dụng di động của phụ huynh',
            
            // ProtectionSection
            protectionTitle: 'BẢO VỆ TRẺ AN TOÀN TRÊN INTERNET',
            protectionFeature1: 'KidoLock giúp cha mẹ chủ động bảo vệ con khỏi nội dung độc hại và nguy cơ trực tuyến',
            protectionFeature2: 'Phát hiện và chặn website có nội dung xấu bằng AI thông minh',
            protectionFeature3: 'Chặn web đen, bạo lực, cờ bạc, và các nội dung không phù hợp với trẻ',
            protectionFeature4: 'Tạo danh sách trắng/đen để kiểm soát chính xác các trang được phép truy cập',
            protectionFeature5: 'Giới hạn thời gian truy cập từng website hoặc phần mềm, hẹn giờ tắt máy tính',
            protectionFeature6: 'Bảo vệ thiết bị di động và máy tính trong cùng một hệ thống quản lý',
            
            // EducationSection
            educationTitle: 'GIÁO DỤC VÀ ĐỊNH HƯỚNG HỌC TẬP',
            educationSubtitle: 'KidoLock không chỉ giúp quản lý thiết bị mà còn khuyến khích trẻ học tập và rèn luyện thói quen tốt:',
            educationFeature1: 'Tích hợp hệ thống bài tập và trò chơi giáo dục giúp trẻ ôn luyện kiến thức mỗi ngày',
            educationFeature2: 'Trẻ nhận điểm thưởng khi hoàn thành bài tập hoặc nhiệm vụ học tập',
            educationFeature3: 'Phụ huynh có thể thưởng thêm thời gian giải trí dựa trên điểm mà con đạt được',
            educationFeature4: 'Giúp trẻ hình thành ý thức tự giác, cân bằng giữa học và chơi, phát triển toàn diện',
            
            // TestimonialsSection
            testimonialsTitle1: 'PHỤ HUYNH',
            testimonialsTitle2: 'NÓI GÌ ?',
            testimonial1Title: 'QUÁ ỔN',
            testimonial1Content: 'Giờ đây, tôi có thể giới hạn việc truy cập của con tôi vào các trang web nhất định trong những giờ cụ thể hoặc chỉ cần tắt máy tính hoàn toàn. Tôi nhận được thông báo ngay lập tức khi con tôi cố truy cập các trang web không được khuyến nghị hoặc bị cấm.',
            testimonial2Title: 'HOÀN HẢO',
            testimonial2Content: 'Tôi thích ứng dụng này. Nó cho phép tôi theo dõi hoạt động của con tôi và kiểm soát thời điểm con có thể truy cập các trang web nhất định. Tôi thích việc con có thể yêu cầu quyền truy cập từ máy tính xách tay của mình và sau đó tôi có thể chỉ cần phê duyệt hoặc từ chối yêu cầu này từ điện thoại của tôi.',
            testimonial3Title: 'VƯỢT KÌ VỌNG',
            testimonial3Content: 'Tôi có thể theo dõi con trực tiếp từ xa kể cả khi tôi đang trong giờ làm việc, có cả giao bài tập và chỉ định giờ cho các ứng dụng và website mà con tôi có thể truy cập nên tôi có thể cài đặt được các hoạt động sử dụng thiết bị điện tử phù hợp với lịch học của con.Tôi còn có thể xem lại ảnh màn hình để thực sự biết được con tôi đã làm gì với laptop của nó.',
            
            // PricingSection
            pricingSubtitle: 'CÁC GÓI DỊCH VỤ',
            pricingTitle1: 'CHỌN GÓI PHÙ HỢP',
            pricingTitle2: 'VỚI BẠN',
            otherPackages: 'CÁC GÓI KHÁC',
            viewDetails: 'XEM CHI TIẾT',
            loadingPackages: 'Đang tải gói dịch vụ...',
            deviceUser: '1 thiết bị | 1 người dùng',
            freeTrial: 'GÓI DÙNG THỬ',
            free: 'MIỄN PHÍ',
            
            // DownloadSection
            downloadHeader1: 'TẢI APP NGAY TẠI',
            downloadHeader2Left: 'MỌI NỀN TẢNG',
            downloadHeader2Right: 'THIẾT BỊ',
            downloadExe: 'TẢI FILE EXE',
            preparingDownload: 'Đang chuẩn bị',
            downloading: 'Đang tải xuống',
            downloadTitle: 'Tải xuống KidLock',
            tutorialTab: 'Hướng dẫn sử dụng',
            downloadTab: 'Tải xuống',
            selectVersion: 'Chọn phiên bản',
            latestVersion: 'Phiên bản mới nhất',
            latestVersionDesc: 'Phiên bản ổn định với các tính năng mới nhất',
            stableVersionDesc: 'Phiên bản ổn định đã được kiểm tra kỹ lưỡng',
            legacyVersionDesc: 'Phiên bản cũ, chỉ khuyến nghị cho hệ thống cũ',
            packageContents: 'Nội dung gói tải về',
            downloadNow: 'Tải xuống ngay',
            loadingVersions: 'Đang tải danh sách phiên bản...',
            latest: 'Mới nhất',
            forAllDevices: 'Cho tất cả thiết bị',
            requiresInternet: 'Yêu cầu có kết nối internet',
            systemRequirements: 'Yêu cầu về hệ thống',
            windowsTitle: 'Máy tính để bàn và máy tính xách tay chạy Windows®',
            diskSpace: 'Dung lượng ổ đĩa',
            freeDiskSpace: 'dung lượng trống trên ổ cứng',
            cpu: 'Bộ xử lý',
            orHigher: 'trở lên',
            or: 'hoặc',
            memory: 'Bộ nhớ',
            minScreenRes: 'Độ phân giải màn hình tối thiểu',
            androidTitle: 'Điện thoại thông minh và máy tính bảng Android¹',
            os: 'Hệ điều hành',
            iosTitle: 'iPhone và iPad',
            languageSupport: 'Hỗ trợ ngôn ngữ',
            vietnamese: 'Tiếng Việt',
            vietnameseDesc: 'Đảm bảo tính dễ hiểu, dễ sử dụng của hệ thống ở tất cả các nền tảng',
            english: 'Tiếng Anh',
            englishDesc: 'Dịch thuật chuẩn, đảm bảo hỗ trợ song ngữ cho đa dạng người dùng',
            
            // Tutorial Popup
            tutorialTitle: 'Hướng dẫn sử dụng KidLock',
            tutorialClose: 'Đóng',
            tutorialSection1: 'I. Truy cập Kid-Lock',
            tutorialSection2: 'II. Giao diện chính',
            tutorialSection3: 'III. Quản lý phần mềm',
            tutorialSection4: 'IV. Quản lý trang Web',
            tutorialSection5: 'V. Lịch sử truy cập Web',
            tutorialSection6: 'VI. Quản lý theo giờ',
            tutorialSection7: 'VII. Ảnh màn hình',
            tutorialSection8: 'VIII. Lịch sử máy tính',
            tutorialSection9: 'IX. Cài đặt',
            
            // Tutorial Steps
            step1Title: 'Mở thanh System Tray',
            step2Title: 'Chọn biểu tượng KidLock',
            step3Title: 'Giao diện chính',
            step4Title: 'Truy cập Quản lý phần mềm',
            step5Title: 'Cho phép sử dụng phần mềm',
            step5Desc: 'Người dùng cho phép các ứng dụng đó được phép truy cập vào.',
            step6Title: 'Bỏ cho phép sử dụng phần mềm',
            step6Desc: 'Người dùng không cho phép các ứng dụng đó được phép truy cập vào nữa.',
            step7Title: 'Cho phép các ứng dụng đang chạy',
            step7Desc: 'Những ứng dụng đang mở sẽ được chưa phép cập nhật',
            step8Title: 'Thiết lập thời gian được phép truy cập của ứng dụng',
            step8Desc: 'Người dùng cài đặt thời gian để cho phép ứng dụng được phép truy cập trong 1 khoảng thời gian nhất định.',
            step9Title: 'Load lại các ứng dụng',
            step9Desc: 'Mỗi khi cài đặt ứng dụng mới thì load lại để cập nhật thêm ứng dụng',
            step10Title: 'Tìm kiếm ứng dụng',
            step11Title: 'Truy cập Quản lý trang Web',
            step12Title: 'Thêm từ khóa cho phép/ Chặn sử dụng trang Web',
            step12Desc: 'Thêm các từ khóa vào list để có thể truy cập/chặn các trang Web có từ khóa trong list.',
            step13Title: 'Xóa từ khóa cho phép/ Chặn sử dụng trang Web',
            step13Desc: 'Xóa các từ khóa vào list.',
            step14Title: 'Thiết lập thời gian được phép truy cập của trang Web',
            step14Desc: 'Người dùng được phép truy cập trang Web trong thời gian cho phép.',
            step15Title: 'Xóa toàn bộ cài đặt thời gian',
            step15Desc: 'Tất cả thời gian đã cài đặt sẽ bị xóa hết',
            step16Title: 'Tải các từ khóa mẫu',
            step16Desc: 'Tải các từ khóa mẫu có sẵn',
            step17Title: 'Xem lịch sử truy cập trang Web',
            step18Title: 'Truy cập Lịch sử trang Web',
            step19Title: 'Xem lịch sử truy cập trang Web theo ngày',
            step19Desc: 'Xem lịch sử theo ngày tùy chọn',
            step20Title: 'Truy cập Quản lý theo giờ',
            step21Title: 'Xem lịch sử truy cập trang Web',
            step21Desc: 'Chọn thời gian, trong khoảng thời gian đó người dùng được thoải mái truy cập tất cả các trang Web, ứng dụng mà không bị giới hạn gì.',
            step22Title: 'Truy cập ảnh chụp màn hình',
            step23Title: 'Xem ảnh màn hình đã được chụp',
            step23Desc: 'Xem các ảnh màn hình đã được chụp.',
            step24Title: 'Truy cập Lịch sử máy tính',
            step25Title: 'Xem lịch sử trang Web/ Phần mềm',
            step25Desc: 'Xem lịch sử trang Web/ phần mềm như thời gian sử dụng, thời gian bắt đầu sử dụng, tên,....Cho phép tìm kiếm, chọn ngày xem.',
            step26Title: 'Xem lịch sử trang Web hoặc phần mềm theo ngày',
            step26Desc: 'Xem lịch sử trang Web hoặc ứng dụng theo ngày tùy chọn',
            step27Title: 'Truy cập Cài đặt',
            step28Title: 'Xem thông tin người dùng',
            step29Title: 'Chọn thời gian, đường dẫn lưu ảnh chụp màn hình',
            step29Desc: 'Cài đặt chụp ảnh, chọn khoảng thời gian chụp ảnh, nơi lưu trữ ảnh',
            step30Title: 'Chọn các cài đặt về chặn',
            step30Desc: 'Tùy chọn các cài đặt về chặn trang Web, ứng dụng, hiển thị thông báo, thời gian chặn,...',
            step31Title: 'Đổi mật khẩu',
            step31Desc: 'Đổi mật khẩu',
            step32Title: 'Tắt phần mềm hoàn toàn',
            step32Desc: 'Phần mềm bị tắt hoàn toàn',
            
            // PricingSection translations
            standardPackage: 'GÓI TIÊU CHUẨN',
            premiumPackage: 'GÓI TRẢ PHÍ',
            contactConsultation: 'LIÊN HỆ TƯ VẤN',
            kidolockBasic: 'Kidolock Basic',
            kidolockPremium: 'Kidolock Premium',
            deviceUser: 'thiết bị | 1 người dùng',
            protectionFeatures: 'Tính năng bảo vệ',
            free: 'MIỄN PHÍ',
            unlimitedTime: 'Không giới hạn thời gian',
            buyNow: 'MUA NGAY',
            contactNow: 'LIÊN HỆ NGAY',
            contactDescription: 'Liên hệ với chúng tôi để được tư vấn về gói dịch vụ phù hợp nhất',
            device: 'thiết bị',
            year: 'Năm',
            save5: 'Tiết kiệm 5%',
            save10: 'Tiết kiệm 10%',
            trialPackage: 'GÓI DÙNG THỬ',
            vnd: 'vnd',
            
            // Modal translations
            standardPackageModal: 'GÓI TIÊU CHUẨN',
            premiumPackageModal: 'GÓI TRẢ PHÍ',
            deviceUserModal: 'thiết bị | 1 người dùng',
            freeTrialModal: 'GÓI DÙNG THỬ',
            freeModal: 'MIỄN PHÍ',
            originalPrice: 'Giá gốc',
            currentPrice: 'Giá hiện tại',
            
            // Contact addresses (values)
            addressMainValue: 'Phòng 901B nhà Thí Nghiệm, Trường Đại học Xây Dựng Hà Nội, số 55 Giải Phóng, Hà Nội',
            address2Value: 'Khu vực trường Kiến Trúc - Văn Quán, Hà Đông, Hà Nội',
            address3Value: 'Trung Tâm Bồi Dưỡng Chính Trị Quận Phú Nhuận - Số 178 Đường Lê Văn Sỹ, P.10, Q. Phú Nhuận, TPHCM',
            address4Value: 'Trường Cao Đẳng Xây Dựng TPHCM, SỐ 190, Võ Văn Ngân, P.Linh Chiểu, Q. Thủ Đức, TPHCM',

            // SubscriptionWorkflowSection
            subscriptionHeader1: 'CÁCH THỨC HOẠT ĐỘNG CỦA',
            subscriptionHeader2: 'GÓI ĐĂNG KÝ',
            pricingLevels: 'CÁC MỨC GIÁ',
            subscriptionCommonDesc: 'Gói đăng ký của bạn sẽ tự động gia hạn mỗi kỳ cho đến khi bạn hủy bỏ gói đăng ký. Để đảm bảo chức năng bảo vệ không bị gián đoạn, chúng tôi sẽ cố gắng tính phí qua phương thức thanh toán của bạn 20 ngày trước khi gói đăng ký của bạn kết thúc. Chúng tôi sẽ thông báo cho bạn về lần tự động gia hạn sắp tới qua email.',
            autoRenewal: 'TỰ ĐỘNG GIA HẠN',
            cancelAutoRenewal: 'HỦY BỎ TỰ ĐỘNG GIA HẠN',
            cancelIntro1: 'Bạn có thể hủy bỏ tự động gia hạn gói đăng ký của mình bất cứ lúc nào.',
            cancelIntro2: 'Nếu bạn hủy bỏ, bạn sẽ được bảo vệ đầy đủ đến khi kết thúc kỳ mà đã thanh toán. Sau ngày này, gói đăng ký của bạn sẽ kết thúc và bạn sẽ không bị tính phí cho bất kỳ khoảng thời gian nào sau này.',
            cancelHowTo: 'Để hủy bỏ:',
            cancelList1: 'Mở biên nhận qua email mà bạn nhận được sau lần mua hàng đầu tiên hoặc email có nhắc nhở tự động gia hạn.',
            cancelList2: 'Truy cập vào liên kết đến trang chứa các điều kiện tự động gia hạn gói đăng ký của bạn.',
            cancelList3: 'Chọn Hủy bỏ tự động gia hạn. Bạn sẽ sớm nhận được email xác nhận việc hủy bỏ tự động gia hạn.',
            cancelSupport: 'Bạn cũng có thể hủy bỏ tự động gia hạn bằng cách liên hệ với bộ phận Hỗ trợ khách hàng của Kidolock.',
            refundIntro: 'Nếu bạn đã bị trừ tiền cho kỳ gói đăng ký tiếp theo, bạn có 30 ngày kể từ ngày thanh toán để yêu cầu hoàn lại toàn bộ khoản thanh toán gia hạn.',
            refundContact: 'Để yêu cầu hoàn tiền, vui lòng liên hệ với bộ phận Hỗ trợ khách hàng của Kidolock.',
            
            // ContactSection
            contactTitle: 'HÃY ĐỂ CHÚNG TÔI LIÊN LẠC VỚI BẠN',
            emailPlaceholder: 'nhập email của bạn',
            send: 'GỬI',
            rdsicTitle: 'Viện Tin Học Xây Dựng',
            rdsicSubtitle: 'Thương hiệu thuộc Trường Đại Học Xây Dựng Hà Nội',
            mainOffice: 'Trụ sở chính :',
            trainingAddress2: 'Địa chỉ đào tạo 2 :',
            trainingAddress3: 'Địa chỉ đào tạo 3 :',
            trainingAddress4: 'Địa chỉ đào tạo 4 :',
            contactInfo: 'THÔNG TIN LIÊN HỆ',
            hotline: 'Hotline :',
            email: 'Email :',
            website: 'Website :',
            copyright: '@2025 RDSIC ALL RIGHTS RESERVED',
            
            // Auth Pages
            loginTitle: 'ĐĂNG NHẬP',
            registerTitle: 'ĐĂNG KÝ',
            resetPasswordTitle: 'ĐẶT LẠI MẬT KHẨU',
            changePasswordTitle: 'ĐỔI MẬT KHẨU',
            emailLabel: 'Email',
            phoneLabel: 'Số điện thoại',
            passwordLabel: 'Mật khẩu',
            confirmPasswordLabel: 'Xác nhận mật khẩu',
            newPasswordLabel: 'Mật khẩu mới',
            currentPasswordLabel: 'Mật khẩu hiện tại',
            forgotPassword: 'Quên mật khẩu?',
            rememberMe: 'Ghi nhớ đăng nhập',
            loginButton: 'ĐĂNG NHẬP',
            registerButton: 'ĐĂNG KÝ',
            resetPasswordButton: 'ĐẶT LẠI MẬT KHẨU',
            changePasswordButton: 'ĐỔI MẬT KHẨU',
            backToLogin: 'Quay lại đăng nhập',
            alreadyHaveAccount: 'Đã có tài khoản?',
            dontHaveAccount: 'Chưa có tài khoản?',
            createAccount: 'Tạo tài khoản',
            loginHere: 'Đăng nhập tại đây',
            // Register page extra
            infoStep: 'Thông tin',
            verifyStep: 'Xác thực',
            fillAllFields: 'Vui lòng điền đầy đủ thông tin',
            pwdNotMeet: 'Mật khẩu chưa đáp ứng yêu cầu bảo mật',
            confirmPwdNotMatch: 'Mật khẩu xác nhận không khớp',
            invalidEmail: 'Email không hợp lệ',
            invalidPhone: 'Số điện thoại không hợp lệ',
            otpSent: 'Mã OTP đã được gửi đến số điện thoại của bạn',
            enterOTP: 'Vui lòng nhập mã OTP',
            registerSuccess: 'Đăng ký thành công!',
            sendingOTP: 'Đang gửi OTP...',
            sendOTP: 'Gửi mã OTP',
            verifyingPhone: 'Xác thực số điện thoại',
            otpSentTo: 'Mã OTP đã được gửi đến số điện thoại:',
            otp: 'Mã OTP',
            otpPlaceholder: 'Nhập mã OTP',
            otpValid5Min: 'Mã OTP có hiệu lực trong 5 phút',
            back: 'Quay lại',
            completingRegister: 'Đang đăng ký...',
            completeRegister: 'Hoàn thành đăng ký',
            orText: 'Hoặc',
            loginWithExisting: 'Đăng nhập với tài khoản có sẵn',
            passwordRequirementsTitle: 'Yêu cầu mật khẩu:',
            reqAtLeast6: 'Ít nhất 6 ký tự',
            reqUpper: 'Có ít nhất 1 chữ in hoa (A-Z)',
            reqLower: 'Có ít nhất 1 chữ in thường (a-z)',
            reqNumber: 'Có ít nhất 1 chữ số (0-9)',
            reqSpecial: 'Có ít nhất 1 ký tự đặc biệt (!@#$%^&*...)',
            confirmPwdMismatch: 'Mật khẩu xác nhận không khớp',
            confirmPwdOk: 'Mật khẩu khớp và đạt yêu cầu',
            emailPlaceholder: 'Nhập email của bạn',
            phoneLabel: 'Số điện thoại',
            phonePlaceholder: 'Nhập số điện thoại',
            fullNameLabel: 'Họ và tên',
            fullNamePlaceholder: 'Nhập họ và tên',
            passwordPlaceholder: 'Nhập mật khẩu (ít nhất 6 ký tự)',
            confirmPasswordPlaceholder: 'Nhập lại mật khẩu',
            // Auth flows extra
            changePwdHeader: 'Đổi mật khẩu',
            changePwdSub: 'Thay đổi mật khẩu của bạn một cách an toàn',
            step1EnterPassword: 'Nhập mật khẩu',
            step2VerifyOTP: 'Xác thực OTP',
            pwdReqTitle: 'Yêu cầu mật khẩu:',
            currentPassword: 'Mật khẩu hiện tại',
            newPassword: 'Mật khẩu mới',
            confirmNewPassword: 'Xác nhận mật khẩu mới',
            sendOTP: 'Gửi mã OTP',
            sendingOTP: 'Đang gửi OTP...',
            verifyOTP: 'Xác thực OTP',
            otpSentToPhone: 'Mã OTP đã được gửi đến số điện thoại của bạn',
            otpCode: 'Mã OTP',
            otpPlaceholder: 'Nhập mã OTP',
            otpValidFor: 'Mã OTP có hiệu lực trong 5 phút',
            back: 'Quay lại',
            changePassword: 'Đổi mật khẩu',
            changingPassword: 'Đang đổi mật khẩu...',
            resetPwdHeader: 'Đặt lại mật khẩu',
            goHome: 'Quay lại trang chủ',
            phoneRegistered: 'Số điện thoại đã đăng ký',
            enterRegisteredPhone: 'Nhập số điện thoại đã đăng ký',
            weWillSendOTP: 'Chúng tôi sẽ gửi mã OTP đến số điện thoại này để xác thực',
            verifyingPhone: 'Xác thực số điện thoại',
            otpSentTo: 'Mã OTP đã được gửi đến số điện thoại:',
            resetting: 'Đang đặt lại...',
            
            // Payment & Wallet
            paymentTitle: 'THANH TOÁN',
            walletTitle: 'VÍ CỦA TÔI',
            packageInfo: 'Thông tin gói',
            paymentMethod: 'Phương thức thanh toán',
            totalAmount: 'Tổng số tiền',
            payNow: 'THANH TOÁN NGAY',
            paymentSuccess: 'Thanh toán thành công!',
            paymentFailed: 'Thanh toán thất bại!',
            transactionHistory: 'Lịch sử giao dịch',
            balance: 'Số dư',
            recharge: 'Nạp tiền',
            withdraw: 'Rút tiền',
            // Payment pages (extra)
            loadingInfo: 'Đang tải thông tin...',
            cannotLoadPackage: 'Không thể tải thông tin gói dịch vụ',
            errorOccurred: 'Có lỗi xảy ra',
            backHome: 'Về trang chủ',
            processingPaymentResult: 'Đang xử lý kết quả thanh toán...',
            paymentNotSuccessful: 'Thanh toán không thành công',
            paymentPageHeader: 'Thanh Toán Gói Dịch Vụ',
            completeYourOrder: 'Hoàn tất đơn hàng của bạn',
            featuresIncluded: 'Tính năng bao gồm:',
            paymentInfoHeader: 'Thông Tin Thanh Toán',
            confirmYourOrder: 'Xác nhận đơn hàng của bạn',
            buyerInfo: 'Thông tin người mua:',
            orderSummary: 'Tóm tắt đơn hàng:',
            numDevices: 'Số thiết bị',
            total: 'Tổng cộng:',
            securedByVNPay: 'Thanh toán được bảo mật bởi VNPay',
            processing: 'Đang xử lý...',
            payVNPay: 'Thanh Toán VNPay',
            backToHome: 'Quay lại trang chủ',
            
            // Admin Pages
            adminDashboard: 'BẢNG ĐIỀU KHIỂN ADMIN',
            manageUsers: 'QUẢN LÝ NGƯỜI DÙNG',
            manageChildren: 'QUẢN LÝ TRẺ EM',
            manageDevices: 'QUẢN LÝ THIẾT BỊ',
            managePackages: 'QUẢN LÝ GÓI DỊCH VỤ',
            reports: 'BÁO CÁO',
            statistics: 'THỐNG KÊ',
            settings: 'CÀI ĐẶT',
            logout: 'ĐĂNG XUẤT',
            
            // Wallet Page
            walletTitle: 'VÍ GÓI CỦA TÔI',
            walletSubtitle: 'Quản lý các gói dịch vụ chưa được gán thiết bị',
            totalUnassignedPackages: 'Tổng gói chưa gán',
            searchPlaceholder: 'Tên gói hoặc mã đơn...',
            sortByDate: 'Ngày mua',
            sortByPrice: 'Giá',
            sortByName: 'Tên gói',
            sortOrder: 'Thứ tự',
            sortOrderNewest: 'Mới nhất',
            sortOrderOldest: 'Cũ nhất',
            priceRange: 'Khoảng giá',
            priceRangeAll: 'Tất cả',
            priceRangeUnder100k: 'Dưới 100k',
            priceRange100k500k: '100k - 500k',
            priceRangeOver500k: 'Trên 500k',
            showingResults: 'Hiển thị',
            of: 'của',
            packages: 'gói',
            clearFilters: 'Xóa bộ lọc',
            noPackagesYet: 'Chưa có gói nào',
            noPackagesDescription: 'Bạn chưa có gói dịch vụ nào chưa được gán thiết bị',
            buyServicePackage: 'Mua gói dịch vụ',
            noPackagesFound: 'Không tìm thấy gói',
            noPackagesFoundDescription: 'Không có gói nào phù hợp với bộ lọc hiện tại',
            packagePrice: 'Giá:',
            purchaseDate: 'Ngày mua:',
            orderCode: 'Mã đơn:',
            features: 'Tính năng:',
            moreFeatures: 'tính năng khác',
            assignDevice: 'Gán Thiết Bị',
            backToHome: 'Về trang chủ',
            loadingWallet: 'Đang tải ví gói...',
            errorOccurred: 'Có lỗi xảy ra',
            cannotLoadWalletData: 'Không thể tải dữ liệu ví gói',
            month: 'THÁNG',
            year: 'NĂM',
            years: 'NĂM',
            
            // Contact Floating Buttons
            hotline: 'Hotline',
            hotlineDescription: 'Liên hệ với chúng tôi để được hỗ trợ',
            hotlineTime: 'Thời gian: 8:00 - 22:00',
            callNow: 'Gọi ngay',
            close: 'Đóng',
            
            // Partner Contact Form
            needMoreDevices: 'Bạn cần thêm thiết bị?',
            needMoreDevicesNote: 'Bạn cần thêm thiết bị? Hãy liên hệ ngay với chúng tôi',
            becomePartner: 'Trở thành đối tác của Kidolocks',
            partnerDescription: 'Liên hệ với chúng tôi để được tư vấn về gói dịch vụ phù hợp với nhu cầu của bạn',
            deviceCount: 'Số thiết bị',
            years: 'Số năm',
            businessName: 'Tên doanh nghiệp/cá nhân',
            contactNow: 'Liên hệ ngay',
            partnerFormTitle: 'Thông tin liên hệ',
            
            // New Partner Form
            becomeOurPartner: 'Trở thành đối tác của chúng tôi',
            kidolockPartner: 'Kidolock Partner',
            partnerSlogan: 'Nhiều thiết bị, nhiều tiện ích - Đối tác của Kidolock luôn được ưu đãi đặc biệt',
            phoneOrEmail: 'Số điện thoại hoặc Email',
            callNow: 'Gọi ngay',
            sendEmail: 'Gửi email',
            emailSent: 'Chúng tôi sẽ sớm liên hệ lại với bạn',

            // Session2 translations
            session2Title: 'GIẢI PHÁP AN TOÀN CHO TRẺ TRONG THẾ GIỚI TRỰC TUYẾN',
            session2Content1: '<span className="font-semibold">KidoLock</span> (Kid Online Lock) là một sản phẩm thuộc hệ sinh thái <span className="font-semibold">Kilovia</span> (Kid Online Via), được nghiên cứu và phát triển bởi <span className="font-semibold">Viện Tin Học Xây Dựng – Trường Đại học Xây Dựng Hà Nội</span>.',
            session2Content2: '<span className="font-semibold">KidoLock</span> mang sứ mệnh đồng hành cùng cha mẹ trong việc bảo vệ, định hướng và giáo dục trẻ em sử dụng Internet một cách <span className="font-semibold">an toàn, thông minh và cân bằng</span>.',
            
            // Session3 translations
            session3Title1: 'QUẢN LÝ VÀ ĐỊNH HƯỚNG TRẺ EM',
            session3Title2: 'TRONG MÔI TRƯỜNG SỐ',
            session3DesktopTitle: 'KIDOLOCK DESKTOP',
            session3DesktopContent: 'Ứng dụng cài trên máy tính giúp kiểm soát việc trẻ sử dụng máy tính, phần mềm và truy cập Internet.',
            session3MobileTitle: 'KIDOLOCK MOBILE',
            session3MobileContent: 'Phiên bản dành cho thiết bị Android, giúp giới hạn thời gian sử dụng và truy cập nội dung trực tuyến.',
            session3ParentTitle: 'KIDOLOCK PARENT APP',
            session3ParentContent: 'Ứng dụng dành cho cha mẹ, cho phép theo dõi, thống kê và điều khiển hoạt động của trẻ từ xa.',
            
            // Session4 translations
            session4Title: 'HỆ SINH THÁI',
            session4Content: 'Bao gồm các bài tập, trò chơi giáo dục giúp trẻ rèn luyện kiến thức Toán, Tiếng Việt, kỹ năng mềm và tư duy logic.',
            session4AiTitle: 'TÍCH HỢP AI',
            session4AiFeature1: 'Gợi ý từng bước giải bài tập.',
            session4AiFeature2: 'Hướng dẫn tư duy thay vì cho đáp án.',
            session4AiFeature3: 'Đề xuất bài học phù hợp năng lực của từng trẻ.',
            session4LearnPlayTitle: 'VỪA HỌC VỪA CHƠI',
            session4LearnPlayFeature1: 'Làm bài tập tích điểm',
            session4LearnPlayFeature2: 'Quy đổi thành thời gian giải trí',
            
            // Session5 translations
            session5Title1: 'SỨ MỆNH CỦA',
            session5Title2: 'KIDOLOCK',
            session5Content: 'Trong thời đại số, Internet vừa là kho tri thức vô hạn, vừa tiềm ẩn nhiều rủi ro. Sứ mệnh của KidoLock là giúp cha mẹ bảo vệ, định hướng và nuôi dưỡng con trong môi trường số an toàn – lành mạnh – cân bằng.',
            session5Subtitle1: 'MỘT PHẦN MỀM',
            session5Subtitle2: 'MỘT NGƯỜI BẠN',
            session5Description: 'Chúng tôi không chỉ tạo ra một phần mềm kiểm soát, mà là <span className="font-semibold" style="color: #1e40af">người bạn đồng hành thông minh</span> của gia đình Việt.',
            session5Benefit1: 'Giúp trẻ sử dụng thiết bị đúng cách, học tập hiệu quả, giải trí lành mạnh...',
            session5Benefit2: 'Giúp cha mẹ yên tâm theo dõi, hướng dẫn con trên hành trình trưởng thành kỹ thuật số',
            
            // Session6 translations
            session6Quote: '"Khi công nghệ được định hướng đúng, nó trở thành sức mạnh giúp trẻ phát triển toàn diện – cả về tri thức và nhân cách."',
            session6Author: 'Khuyết danh',
            
            // FinalSession translations
            finalSessionLabel: 'ĐƠN VỊ',
            finalSessionTitle: 'HỢP TÁC PHÁT TRIỂN',
            finalSessionContent: '<strong>KidoLock và hệ sinh thái Kilovia</strong> được phát triển thông qua sự hợp tác giữa sinh viên và giảng viên của <strong>Viện Tin Học Xây Dựng – Trường Đại học Xây Dựng</strong>, cùng với các thầy cô giáo của <strong>Tiểu học Thị trấn Cổ Lễ</strong> thuộc huyện Trực Ninh, tỉnh Ninh Bình. Sự kết hợp giữa <strong>công nghệ học thuật</strong> và <strong>kinh nghiệm sư phạm thực tế</strong> đã tạo ra một sản phẩm hiện đại, hữu ích và gần gũi với giáo dục Việt Nam.',
            finalSessionCopyright: '© Bản quyền',
            finalSessionCopyrightText1: 'Bản quyền thuộc Viện Tin Học Xây Dựng - Trường Đại học Xây Dựng Hà Nội.',
            finalSessionCopyrightText2: 'Mọi quyền được bảo lưu. Việc sao chép, chỉnh sửa hoặc sử dụng lại sản phẩm cần có sự đồng ý bằng văn bản của Viện Tin Học Xây Dựng.',
            
            // Common Actions
            save: 'LƯU',
            cancel: 'HỦY',
            delete: 'XÓA',
            edit: 'SỬA',
            add: 'THÊM',
            search: 'TÌM KIẾM',
            filter: 'LỌC',
            export: 'XUẤT',
            import: 'NHẬP',
            refresh: 'LÀM MỚI',
            loading: 'Đang tải...',
            error: 'Lỗi',
            success: 'Thành công',
            warning: 'Cảnh báo',
            info: 'Thông tin',
            confirm: 'Xác nhận',
            yes: 'Có',
            no: 'Không',
            ok: 'OK',
            close: 'Đóng'
        },
        en: {
            // Navbar
            home: 'HOME',
            features: 'FEATURES',
            pricing: 'PRICING',
            download: 'DOWNLOAD',
            contact: 'CONTACT',
            login: 'LOGIN',
            register: 'REGISTER',
            language: 'Language',
            country: 'Country/Region',
            // Navbar extra
            navForFamily: 'For family',
            navForBusiness: 'For business',
            navPartners: 'Partners',
            navAboutUs: 'About us',
            familyHeader: 'For family',
            businessHeader: 'For business',
            partnersHeader: 'Partners',
            aboutHeader: 'About us',
            mobileAccount: 'Account',
            viewAllSolutions: 'View all solutions',
            viewAllBusinessSolutions: 'View all business solutions',
            // Navbar labels
            securitySolutions: 'Security solutions',
            privacyAndKids: 'Privacy & Kids',
            licenseRenewal: 'License renewal',
            support: 'Support',
            trialsAndDownloads: 'Trials & Downloads',
            businessSolutions: 'Business solutions',
            enterpriseSecurityLabel: 'ENTERPRISE SECURITY',
            centralizedMgmtLabel: 'CENTRALIZED MANAGEMENT',
            cloudSecurityLabel: 'CLOUD SECURITY',
            downloads: 'Downloads',
            businessSupport: 'Business support',
            trainingAndCerts: 'Training & Certifications',
            partnerProgram: 'Partner program',
            findPartners: 'Find partners',
            providersForBusiness: 'Providers for business',
            providersForConsumers: 'Consumer solution providers',
            distributorsPartners: 'Partner with distributors',
            findLearningCenter: 'Find a learning center',
            becomePartner: 'Become a partner',
            unitedPortal: 'Kidolock United partner portal',
            becomeB2B: 'Become a B2B partner',
            becomeB2C: 'Become a B2C partner',
            bestSeller: 'BESTSELLER',
            familyPremiumTier: 'PREMIUM PROTECTION',
            familyAdvancedTier: 'ADVANCED PROTECTION',
            familyStandardTier: 'STANDARD PROTECTION',
            premiumName: 'Kidolock Premium',
            plusName: 'Kidolock Plus',
            standardName: 'Kidolock Standard',
            premiumDesc: 'Comprehensive protection for your devices, privacy & online identity',
            plusDesc: 'Combines security, performance & privacy features in one app',
            standardDesc: 'Enhanced protection with device performance boosting tools',
            userMgmtLabel: 'USER MANAGEMENT FEATURES',
            safeKidsName: 'Kidolock Safe Kids',
            safeKidsDesc: 'Flexible parental controls & GPS tracking for your children.',
            vpnLabel: 'VPN',
            vpnName: 'Kidolock VPN Secure Connection',
            vpnDesc: 'Private and secure VPN to enjoy the internet without sacrificing speed.',
            pwdProtectLabel: 'PASSWORD PROTECTION',
            pwdMgrName: 'Kidolock Password Manager',
            pwdMgrDesc: 'Bank-grade secure vault for your passwords & documents.',
            businessSecurityName: 'Kidolock Business Security',
            businessSecurityDesc: 'Comprehensive protection for enterprise networks, endpoints and critical data',
            enterpriseSecurityName: 'Kidolock Enterprise Security',
            enterpriseSecurityDesc: 'Centralized security management solution for large enterprises',
            cloudSecurityName: 'Kidolock Cloud Security',
            cloudSecurityDesc: 'Secure your data and applications in the cloud safely',
            aboutUs: 'About us',
            learnAboutUs: 'Learn about us',
            contactUs: 'Contact us',
            careers: 'Careers',
            media: 'Media',
            pressCenter: 'Press center',
            pressReleases: 'Press releases',
            sponsorships: 'Sponsorships',
            wallet: 'Wallet',
            purchaseHistory: 'Purchase history',
            comingSoon: 'Coming soon',
            logoutLabel: 'Logout',
            loginLabel: 'Login',
            registerLabel: 'Register',
            adminLabel: 'Administrator',
            parentLabel: 'Parent',
            adminRole: 'ADMIN',
            premiumRole: 'PREMIUM',
            mobileAccount: 'Account',
            
            // HomePage Banner
            breadcrumbHome: 'HOME',
            breadcrumbKidolock: 'KIDOLOCK',
            mainTitle: 'KIDOLOCK',
            subtitle1: 'SOFTWARE THAT HELPS PARENTS CONTROL,',
            subtitle2: 'LIMIT AND PROTECT CHILDREN',
            subtitle3_prefix: '',
            subtitle3_highlight_trash_internet: 'WHEN USING THE INTERNET ',
            subtitle3_suffix: 'ANYTIME - ANYWHERE',
            feature1_prefix: 'TRACK AND MANAGE WHAT YOUR CHILDREN WATCH ON ',
            feature1_highlight_internet: 'INTERNET',
            feature1_suffix: '',
            feature2_prefix: 'LIMIT YOUR CHILD\'S ',
            feature2_highlight_online: '"ONLINE"',
            feature2_suffix: ' TIME',
            feature3_prefix: 'PARENTS PEACE OF MIND, REMOTE MONITORING VIA PHONE OR COMPUTER',
            feature3_highlight_anywhere: '',
            feature3_suffix: '',
            availableOn: 'AVAILABLE ON',
            
            // WhyKidolock
            whyTitle1: 'WHY',
            whyTitle2: 'KIDOLOCK ?',
            protectTitle: 'PROTECT',
            protectContent: 'Using AI technology, KidoLock automatically detects and blocks dangerous content such as violence, gambling, or pornography. Parents can be completely at ease when their children study and explore the Internet every day.',
            trackTitle: 'TRACK',
            trackContent: 'Kidolock helps parents track their children\'s online activities subtly and safely — to understand them better, provide better guidance, and protect them from Internet risks.',
            educateTitle: 'EDUCATE',
            educateContent: 'Smart "reward-punishment" mechanism turns learning into an active habit. Children can be rewarded with extra entertainment time when completing homework, creating positive and more self-disciplined learning motivation every day.',
            
            // FeaturesSection
            featuresTitle1: 'TRACK CHILDREN\'S ACTIVITIES',
            featuresTitle2: '',
            featuresSubtitle: 'Help parents track all their children\'s computer activities safely and visually:',
            feature1: 'Record website access history and software usage',
            feature2: 'Take periodic screenshots for easy parental control',
            feature3: 'Detailed statistics of time spent on each website and application',
            feature4: 'Synchronize all data and reports to parents\' mobile application',
            
            // ProtectionSection
            protectionTitle: 'PROTECT CHILDREN SAFELY ON THE INTERNET',
            protectionFeature1: 'KidoLock helps parents proactively protect their children from harmful content and online risks',
            protectionFeature2: 'Detect and block websites with bad content using smart AI',
            protectionFeature3: 'Block adult sites, violence, gambling, and content inappropriate for children',
            protectionFeature4: 'Create whitelist/blacklist to precisely control which pages are allowed to access',
            protectionFeature5: 'Limit access time for each website or software, schedule computer shutdown',
            protectionFeature6: 'Protect mobile devices and computers in the same management system',
            
            // EducationSection
            educationTitle: 'EDUCATION AND LEARNING GUIDANCE',
            educationSubtitle: 'KidoLock not only helps manage devices but also encourages children to study and develop good habits:',
            educationFeature1: 'Integrated homework system and educational games help children review knowledge daily',
            educationFeature2: 'Children earn reward points when completing homework or learning tasks',
            educationFeature3: 'Parents can reward extra entertainment time based on points their children achieve',
            educationFeature4: 'Help children develop self-awareness, balance between study and play, comprehensive development',
            
            // TestimonialsSection
            testimonialsTitle1: 'PARENTS',
            testimonialsTitle2: 'SAY WHAT ?',
            testimonial1Title: 'TOO GOOD',
            testimonial1Content: 'Now I can limit my child\'s access to certain websites at specific hours or just turn off the computer completely. I get instant notifications when my child tries to access unrecommended or blocked websites.',
            testimonial2Title: 'PERFECT',
            testimonial2Content: 'I like this app. It allows me to track my child\'s activities and control when they can access certain websites. I like that they can request access from their laptop and then I can just approve or deny this request from my phone.',
            testimonial3Title: 'EXCEEDS EXPECTATIONS',
            testimonial3Content: 'I can update more than expected what I want to know about my children\'s digital life. I can know where they are, where they have been and even tell them if they need to charge their iPhones – and I\'m using Android without any problems.',
            
            // PricingSection
            pricingSubtitle: 'SERVICE PACKAGES',
            pricingTitle1: 'CHOOSE THE PACKAGE',
            pricingTitle2: 'THAT SUITS YOU',
            otherPackages: 'OTHER PACKAGES',
            viewDetails: 'VIEW DETAILS',
            loadingPackages: 'Loading packages...',
            deviceUser: '1 device | 1 user',
            freeTrial: 'TRIAL PACKAGE',
            free: 'FREE',
            
            // DownloadSection
            downloadHeader1: 'DOWNLOAD THE APP ON',
            downloadHeader2Left: 'ALL PLATFORMS',
            downloadHeader2Right: 'DEVICES',
            downloadExe: 'DOWNLOAD EXE',
            preparingDownload: 'Preparing',
            downloading: 'Downloading',
            downloadTitle: 'Download KidLock',
            tutorialTab: 'User Guide',
            downloadTab: 'Download',
            selectVersion: 'Select Version',
            latestVersion: 'Latest Version',
            latestVersionDesc: 'Stable version with the latest features',
            stableVersionDesc: 'Stable version that has been thoroughly tested',
            legacyVersionDesc: 'Legacy version, only recommended for older systems',
            packageContents: 'Package Contents',
            downloadNow: 'Download Now',
            loadingVersions: 'Loading versions...',
            latest: 'Latest',
            forAllDevices: 'For all devices',
            requiresInternet: 'Requires internet connection',
            systemRequirements: 'System requirements',
            windowsTitle: 'Windows® desktops and laptops',
            diskSpace: 'Disk space',
            freeDiskSpace: 'free disk space',
            cpu: 'CPU',
            orHigher: 'or higher',
            or: 'or',
            memory: 'Memory',
            minScreenRes: 'Minimum screen resolution',
            androidTitle: 'Android smartphones and tablets¹',
            os: 'Operating system',
            iosTitle: 'iPhone and iPad',
            languageSupport: 'Language support',
            vietnamese: 'Vietnamese',
            vietnameseDesc: 'Ensures ease of understanding and use across all platforms',
            english: 'English',
            englishDesc: 'Accurate translation, providing bilingual support for diverse users',
            
            // New Navbar structure
            products: 'Products',
            mainFeatures: 'Main Features',
            protectionFeatures: 'Protection Features',
            childProtection: 'Child Protection',
            safeEducation: 'Safe Education',
            pricingAndReviews: 'Pricing & Reviews',
            pricingTable: 'Pricing Table',
            reviews: 'Reviews',
            download: 'Download',
            android: 'Android',
            ios: 'iOS',
            windows: 'Windows',
            androidDesc: 'Download for Android',
            iosDesc: 'Download for iOS',
            windowsDesc: 'Download for Windows',
            androidDeveloping: 'Under Development',
            iosDeveloping: 'Under Development',
            windowsWorking: 'Download for Windows',
            
            // Tutorial Popup
            tutorialTitle: 'KidLock User Guide',
            tutorialClose: 'Close',
            tutorialSection1: 'I. Access Kid-Lock',
            tutorialSection2: 'II. Main Interface',
            tutorialSection3: 'III. Software Management',
            tutorialSection4: 'IV. Web Management',
            tutorialSection5: 'V. Web Access History',
            tutorialSection6: 'VI. Time Management',
            tutorialSection7: 'VII. Screenshots',
            tutorialSection8: 'VIII. Computer History',
            tutorialSection9: 'IX. Settings',
            
            // Tutorial Steps
            step1Title: 'Open System Tray',
            step2Title: 'Select KidLock Icon',
            step3Title: 'Main Interface',
            step4Title: 'Access Software Management',
            step5Title: 'Allow Software Usage',
            step5Desc: 'Users allow those applications to be granted access.',
            step6Title: 'Disallow Software Usage',
            step6Desc: 'Users no longer allow those applications to be granted access.',
            step7Title: 'Allow Running Applications',
            step7Desc: 'Currently open applications will be allowed to update.',
            step8Title: 'Set Application Access Time',
            step8Desc: 'Users set time to allow applications to be granted access for a specific period.',
            step9Title: 'Reload Applications',
            step9Desc: 'Every time a new application is installed, reload to update additional applications.',
            step10Title: 'Search Applications',
            step11Title: 'Access Web Management',
            step12Title: 'Add Keywords for Allow/Block Web Usage',
            step12Desc: 'Add keywords to the list to access/block websites containing keywords in the list.',
            step13Title: 'Delete Keywords for Allow/Block Web Usage',
            step13Desc: 'Delete keywords from the list.',
            step14Title: 'Set Web Access Time',
            step14Desc: 'Users are allowed to access websites during permitted time.',
            step15Title: 'Delete All Time Settings',
            step15Desc: 'All set time will be deleted.',
            step16Title: 'Load Sample Keywords',
            step16Desc: 'Load available sample keywords.',
            step17Title: 'View Web Access History',
            step18Title: 'Access Web History',
            step19Title: 'View Web Access History by Date',
            step19Desc: 'View history by selected date.',
            step20Title: 'Access Time Management',
            step21Title: 'View Web Access History',
            step21Desc: 'Select time, during which users can freely access all websites and applications without any restrictions.',
            step22Title: 'Access Screenshots',
            step23Title: 'View Captured Screenshots',
            step23Desc: 'View captured screenshots.',
            step24Title: 'Access Computer History',
            step25Title: 'View Web/Software History',
            step25Desc: 'View web/software history such as usage time, start time, name, etc. Allow search, select date to view.',
            step26Title: 'View Web or Software History by Date',
            step26Desc: 'View web or application history by selected date.',
            step27Title: 'Access Settings',
            step28Title: 'View User Information',
            step29Title: 'Select Time and Path for Screenshot Storage',
            step29Desc: 'Set screenshot capture, select screenshot time interval, storage location.',
            step30Title: 'Select Block Settings',
            step30Desc: 'Choose settings for blocking websites, applications, notifications, block time, etc.',
            step31Title: 'Change Password',
            step31Desc: 'Change password.',
            step32Title: 'Completely Turn Off Software',
            step32Desc: 'Software is completely turned off.',
            
            // PricingSection translations
            standardPackage: 'STANDARD PACKAGE',
            premiumPackage: 'PREMIUM PACKAGE',
            contactConsultation: 'CONTACT CONSULTATION',
            kidolockBasic: 'Kidolock Basic',
            kidolockPremium: 'Kidolock Premium',
            deviceUser: 'device | 1 user',
            protectionFeatures: 'Protection Features',
            free: 'FREE',
            unlimitedTime: 'Unlimited time',
            buyNow: 'BUY NOW',
            contactNow: 'CONTACT NOW',
            contactDescription: 'Contact us for consultation on the most suitable service package',
            device: 'device',
            year: 'Year',
            save5: 'Save 5%',
            save10: 'Save 10%',
            trialPackage: 'TRIAL PACKAGE',
            vnd: 'vnd',
            
            // Modal translations
            standardPackageModal: 'STANDARD PACKAGE',
            premiumPackageModal: 'PREMIUM PACKAGE',
            deviceUserModal: 'device | 1 user',
            freeTrialModal: 'TRIAL PACKAGE',
            freeModal: 'FREE',
            originalPrice: 'Original price',
            currentPrice: 'Current price',
            
            // Contact addresses (values)
            addressMainValue: 'Room 901B, Laboratory Building, Hanoi University of Civil Engineering, 55 Giai Phong, Hanoi',
            address2Value: 'Architecture University area - Van Quan, Ha Dong, Hanoi',
            address3Value: 'Phu Nhuan District Political Training Center - 178 Le Van Sy Street, Ward 10, Phu Nhuan District, HCMC',
            address4Value: 'Ho Chi Minh City College of Construction, 190 Vo Van Ngan, Linh Chieu Ward, Thu Duc City, HCMC',

            // SubscriptionWorkflowSection
            subscriptionHeader1: 'HOW IT WORKS',
            subscriptionHeader2: 'SUBSCRIPTION',
            pricingLevels: 'PRICING LEVELS',
            subscriptionCommonDesc: 'Your subscription will automatically renew each term until you cancel it. To ensure uninterrupted protection, we will attempt to charge your payment method 20 days before your subscription ends. We will notify you about the upcoming auto-renewal via email.',
            autoRenewal: 'AUTO-RENEWAL',
            cancelAutoRenewal: 'CANCEL AUTO-RENEWAL',
            cancelIntro1: 'You can cancel auto-renewal of your subscription at any time.',
            cancelIntro2: 'If you cancel, you will remain fully protected until the end of the paid term. After this date, your subscription will end and you will not be charged for any future periods.',
            cancelHowTo: 'To cancel:',
            cancelList1: 'Open the receipt email you received after your first purchase or the auto-renewal reminder email.',
            cancelList2: 'Follow the link to the page containing your subscription auto-renewal terms.',
            cancelList3: 'Choose Cancel auto-renewal. You will soon receive a confirmation email of the cancellation.',
            cancelSupport: 'You can also cancel auto-renewal by contacting Kidolock Customer Support.',
            refundIntro: 'If you have already been charged for the next subscription term, you have 30 days from the payment date to request a full refund of the renewal charge.',
            refundContact: 'To request a refund, please contact Kidolock Customer Support.',
            
            // ContactSection
            contactTitle: 'LET US CONTACT YOU',
            emailPlaceholder: 'enter your email',
            send: 'SEND',
            rdsicTitle: 'Institute Information technology in civil engineering',
            rdsicSubtitle: 'Brand of Hanoi University of Civil Engineering',
            mainOffice: 'Office :',
            trainingAddress2: 'Training address 2 :',
            trainingAddress3: 'Training address 3 :',
            trainingAddress4: 'Training address 4 :',
            contactInfo: 'CONTACT INFORMATION',
            hotline: 'Hotline :',
            email: 'Email :',
            website: 'Website :',
            copyright: '@2025 RDSIC ALL RIGHTS RESERVED',
            
            // Auth Pages
            loginTitle: 'LOGIN',
            registerTitle: 'REGISTER',
            resetPasswordTitle: 'RESET PASSWORD',
            changePasswordTitle: 'CHANGE PASSWORD',
            emailLabel: 'Email',
            phoneLabel: 'Phone Number',
            passwordLabel: 'Password',
            confirmPasswordLabel: 'Confirm Password',
            newPasswordLabel: 'New Password',
            currentPasswordLabel: 'Current Password',
            forgotPassword: 'Forgot Password?',
            rememberMe: 'Remember Me',
            loginButton: 'LOGIN',
            registerButton: 'REGISTER',
            resetPasswordButton: 'RESET PASSWORD',
            changePasswordButton: 'CHANGE PASSWORD',
            backToLogin: 'Back to Login',
            alreadyHaveAccount: 'Already have an account?',
            dontHaveAccount: "Don't have an account?",
            createAccount: 'Create Account',
            loginHere: 'Login Here',
            // Register page extra
            infoStep: 'Information',
            verifyStep: 'Verification',
            fillAllFields: 'Please fill in all required fields',
            pwdNotMeet: 'Password does not meet security requirements',
            confirmPwdNotMatch: 'Confirmation password does not match',
            invalidEmail: 'Invalid email',
            invalidPhone: 'Invalid phone number',
            otpSent: 'OTP has been sent to your phone number',
            enterOTP: 'Please enter the OTP',
            registerSuccess: 'Registration successful!',
            sendingOTP: 'Sending OTP...',
            sendOTP: 'Send OTP',
            verifyingPhone: 'Phone verification',
            otpSentTo: 'OTP sent to phone number:',
            otp: 'OTP Code',
            otpPlaceholder: 'Enter OTP code',
            otpValid5Min: 'OTP is valid for 5 minutes',
            back: 'Back',
            completingRegister: 'Registering...',
            completeRegister: 'Complete registration',
            orText: 'Or',
            loginWithExisting: 'Login with existing account',
            passwordRequirementsTitle: 'Password requirements:',
            reqAtLeast6: 'At least 6 characters',
            reqUpper: 'At least 1 uppercase letter (A-Z)',
            reqLower: 'At least 1 lowercase letter (a-z)',
            reqNumber: 'At least 1 digit (0-9)',
            reqSpecial: 'At least 1 special character (!@#$%^&*...)',
            confirmPwdMismatch: 'Confirmation password does not match',
            confirmPwdOk: 'Passwords match and meet requirements',
            emailPlaceholder: 'Enter your email',
            phoneLabel: 'Phone number',
            phonePlaceholder: 'Enter phone number',
            fullNameLabel: 'Full name',
            fullNamePlaceholder: 'Enter full name',
            passwordPlaceholder: 'Enter password (at least 6 characters)',
            confirmPasswordPlaceholder: 'Re-enter password',
            
            // Auth flows extra
            changePwdHeader: 'Change password',
            changePwdSub: 'Change your password securely',
            step1EnterPassword: 'Enter password',
            step2VerifyOTP: 'Verify OTP',
            pwdReqTitle: 'Password requirements:',
            currentPassword: 'Current password',
            newPassword: 'New password',
            confirmNewPassword: 'Confirm new password',
            sendOTP: 'Send OTP',
            sendingOTP: 'Sending OTP...',
            verifyOTP: 'Verify OTP',
            otpSentToPhone: 'OTP has been sent to your phone number',
            otpCode: 'OTP Code',
            otpPlaceholder: 'Enter OTP code',
            otpValidFor: 'OTP is valid for 5 minutes',
            back: 'Back',
            changePassword: 'Change password',
            changingPassword: 'Changing password...',
            resetPwdHeader: 'Reset password',
            goHome: 'Back to home',
            phoneRegistered: 'Registered phone number',
            enterRegisteredPhone: 'Enter registered phone number',
            weWillSendOTP: 'We will send OTP to this phone number for verification',
            verifyingPhone: 'Phone verification',
            otpSentTo: 'OTP sent to phone number:',
            resetting: 'Resetting...',
            
            // Payment & Wallet
            paymentTitle: 'PAYMENT',
            walletTitle: 'MY WALLET',
            packageInfo: 'Package Information',
            paymentMethod: 'Payment Method',
            totalAmount: 'Total Amount',
            payNow: 'PAY NOW',
            paymentSuccess: 'Payment Successful!',
            paymentFailed: 'Payment Failed!',
            transactionHistory: 'Transaction History',
            balance: 'Balance',
            recharge: 'Recharge',
            withdraw: 'Withdraw',
            // Payment pages (extra)
            loadingInfo: 'Loading information...',
            cannotLoadPackage: 'Cannot load package information',
            errorOccurred: 'An error occurred',
            backHome: 'Back to home',
            processingPaymentResult: 'Processing payment result...',
            paymentNotSuccessful: 'Payment not successful',
            paymentPageHeader: 'Service Package Payment',
            completeYourOrder: 'Complete your order',
            featuresIncluded: 'Features included:',
            paymentInfoHeader: 'Payment Information',
            confirmYourOrder: 'Confirm your order',
            buyerInfo: 'Buyer information:',
            orderSummary: 'Order summary:',
            numDevices: 'Devices',
            total: 'Total:',
            securedByVNPay: 'Payment secured by VNPay',
            processing: 'Processing...',
            payVNPay: 'Pay with VNPay',
            backToHome: 'Back to home',
            
            // Admin Pages
            adminDashboard: 'ADMIN DASHBOARD',
            manageUsers: 'MANAGE USERS',
            manageChildren: 'MANAGE CHILDREN',
            manageDevices: 'MANAGE DEVICES',
            managePackages: 'MANAGE PACKAGES',
            reports: 'REPORTS',
            statistics: 'STATISTICS',
            settings: 'SETTINGS',
            logout: 'LOGOUT',
            
            // Wallet Page
            walletTitle: 'MY WALLET',
            walletSubtitle: 'Manage unassigned service packages',
            totalUnassignedPackages: 'Total unassigned packages',
            searchPlaceholder: 'Package name or order code...',
            sortByDate: 'Purchase date',
            sortByPrice: 'Price',
            sortByName: 'Package name',
            sortOrder: 'Sort order',
            sortOrderNewest: 'Newest',
            sortOrderOldest: 'Oldest',
            priceRange: 'Price range',
            priceRangeAll: 'All',
            priceRangeUnder100k: 'Under 100k',
            priceRange100k500k: '100k - 500k',
            priceRangeOver500k: 'Over 500k',
            showingResults: 'Showing',
            of: 'of',
            packages: 'packages',
            clearFilters: 'Clear filters',
            noPackagesYet: 'No packages yet',
            noPackagesDescription: 'You don\'t have any unassigned service packages yet',
            buyServicePackage: 'Buy service package',
            noPackagesFound: 'No packages found',
            noPackagesFoundDescription: 'No packages match the current filters',
            packagePrice: 'Price:',
            purchaseDate: 'Purchase date:',
            orderCode: 'Order code:',
            features: 'Features:',
            moreFeatures: 'more features',
            assignDevice: 'Assign Device',
            backToHome: 'Back to home',
            loadingWallet: 'Loading wallet...',
            errorOccurred: 'An error occurred',
            cannotLoadWalletData: 'Cannot load wallet data',
            month: 'MONTH',
            year: 'YEAR',
            years: 'YEARS',
            
            // Contact Floating Buttons
            hotline: 'Hotline :',
            hotlineDescription: 'Contact us for support',
            hotlineTime: 'Time: 8:00 - 22:00',
            callNow: 'Call Now',
            close: 'Close',
            
            // Partner Contact Form
            needMoreDevices: 'Need more devices?',
            needMoreDevicesNote: 'Need more devices? Contact us now',
            becomePartner: 'Become a Kidolocks Partner',
            partnerDescription: 'Contact us for consultation on service packages suitable for your needs',
            deviceCount: 'Number of devices',
            years: 'Number of years',
            businessName: 'Business/Individual name',
            contactNow: 'Contact Now',
            partnerFormTitle: 'Contact Information',
            
            // New Partner Form
            becomeOurPartner: 'Become Our Partner',
            kidolockPartner: 'Kidolock Partner',
            partnerSlogan: 'More devices, more benefits - Kidolock partners always get special privileges',
            phoneOrEmail: 'Phone Number or Email',
            callNow: 'Call Now',
            sendEmail: 'Send Email',
            emailSent: 'We will contact you soon',

            // Session2 translations
            session2Title: 'SAFE SOLUTION FOR CHILDREN IN THE ONLINE WORLD',
            session2Content1: '<span className="font-semibold">KidoLock</span> (Kid Online Lock) is a product of the <span className="font-semibold">Kilovia</span> (Kid Online Via) ecosystem, researched and developed by <span className="font-semibold">Institute of Information Technology in Construction – Hanoi University of Civil Engineering</span>.',
            session2Content2: '<span className="font-semibold">KidoLock</span> carries the mission of accompanying parents in protecting, guiding and educating children to use the Internet in a <span className="font-semibold">safe, smart and balanced</span> way.',

            // Session3 translations
            session3Title1: 'MANAGING AND GUIDING CHILDREN',
            session3Title2: 'IN THE DIGITAL ENVIRONMENT',
            session3DesktopTitle: 'KIDOLOCK DESKTOP',
            session3DesktopContent: 'Application installed on computers to help control children\'s computer usage, software and Internet access.',
            session3MobileTitle: 'KIDOLOCK MOBILE',
            session3MobileContent: 'Version for Android devices, helping to limit usage time and access to online content.',
            session3ParentTitle: 'KIDOLOCK PARENT APP',
            session3ParentContent: 'Application for parents, allowing remote monitoring, statistics and control of children\'s activities.',

            // Session4 translations
            session4Title: 'ECOSYSTEM',
            session4Content: 'Includes educational exercises and games to help children practice Math, Vietnamese, soft skills and logical thinking.',
            session4AiTitle: 'AI INTEGRATION',
            session4AiFeature1: 'Step-by-step exercise solving suggestions.',
            session4AiFeature2: 'Guide thinking instead of giving answers.',
            session4AiFeature3: 'Suggest lessons suitable for each child\'s ability.',
            session4LearnPlayTitle: 'LEARNING WHILE PLAYING',
            session4LearnPlayFeature1: 'Complete exercises to earn points',
            session4LearnPlayFeature2: 'Convert to entertainment time',

            // Session5 translations
            session5Title1: 'MISSION OF',
            session5Title2: 'KIDOLOCK',
            session5Content: 'In the digital age, the Internet is both an infinite source of knowledge and a place with many potential risks. KidoLock\'s mission is to help parents protect, guide and nurture their children in a safe – healthy – balanced digital environment.',
            session5Subtitle1: 'A SOFTWARE',
            session5Subtitle2: 'A FRIEND',
            session5Description: 'We don\'t just create control software, but a <span className="font-semibold" style="color: #1e40af">smart companion</span> for Vietnamese families.',
            session5Benefit1: 'Helps children use devices correctly, learn effectively, entertain healthily...',
            session5Benefit2: 'Helps parents feel secure monitoring, guiding their children on their digital growth journey',

            // Session6 translations
            session6Quote: '"When technology is correctly oriented, it becomes a power that helps children develop comprehensively – both in knowledge and character."',
            session6Author: 'Anonymous',

            // FinalSession translations
            finalSessionLabel: 'UNIT',
            finalSessionTitle: 'DEVELOPMENT COOPERATION',
            finalSessionContent: '<strong>KidoLock and Kilovia ecosystem</strong> were developed through cooperation between students and lecturers from <strong>Institute of Information Technology in Construction – Hanoi University of Civil Engineering</strong>, along with teachers from <strong>Co Le Town Primary School</strong> located in Truc Ninh, Ninh Binh, Vietnam. The combination of <strong>academic technology</strong> and <strong>practical pedagogical experience</strong> has created a modern, useful and relatable product for Vietnamese education.',
            finalSessionCopyright: '© Copyright',
            finalSessionCopyrightText1: 'Copyright belongs to Institute of Information Technology in Construction - Hanoi University of Civil Engineering.',
            finalSessionCopyrightText2: 'All rights reserved. Copying, editing or reusing the product requires written consent from the Institute of Information Technology in Construction.',

            // Common Actions
            save: 'SAVE',
            cancel: 'CANCEL',
            delete: 'DELETE',
            edit: 'EDIT',
            add: 'ADD',
            search: 'SEARCH',
            filter: 'FILTER',
            export: 'EXPORT',
            import: 'IMPORT',
            refresh: 'REFRESH',
            loading: 'Loading...',
            error: 'Error',
            success: 'Success',
            warning: 'Warning',
            info: 'Information',
            confirm: 'Confirm',
            yes: 'Yes',
            no: 'No',
            ok: 'OK',
            close: 'Close'
        }
    };

    const t = (key) => {
        const dict = translations[language] || {};
        return Object.prototype.hasOwnProperty.call(dict, key) ? dict[key] : key;
    };

    const value = {
        language,
        setLanguage,
        toggleLanguage,
        t
    };

    return (
        <LanguageContext.Provider value={value}>
            {children}
        </LanguageContext.Provider>
    );
};
